//! Windows-on-Arm layout constants and shared vocabulary.

pub const WINDOWS_ARM_BOOT_DISK_DEFAULT_SIZE_GIB: u32 = 64;
pub const WINDOWS_ARM_BOOT_DISK_MIN_SIZE_GIB: u32 = 8;
pub const WINDOWS_ARM_UEFI_LOW_CODE_ALIAS_IPA: u64 = 0x0000_0000;
pub const WINDOWS_ARM_UEFI_LOW_VARS_ALIAS_IPA: u64 = 0x0400_0000;
pub const WINDOWS_ARM_UEFI_CODE_IPA: u64 = 0x0800_0000;
pub const WINDOWS_ARM_UEFI_VARS_IPA: u64 = 0x0c00_0000;
pub const WINDOWS_ARM_UEFI_SLOT_BYTES: u64 = 64 * 1024 * 1024;
pub const WINDOWS_ARM_UEFI_PFLASH_BYTES: u64 = WINDOWS_ARM_UEFI_SLOT_BYTES * 2;
pub const WINDOWS_ARM_DEVICE_MMIO_IPA: u64 = 0x1000_0000;
pub const WINDOWS_ARM_DEVICE_MMIO_BYTES: u64 = 0x1000_0000;
pub(crate) const WINDOWS_ARM_PL011_MMIO_IPA: u64 = WINDOWS_ARM_DEVICE_MMIO_IPA;
pub(crate) const WINDOWS_ARM_PL031_MMIO_IPA: u64 = WINDOWS_ARM_DEVICE_MMIO_IPA + 0x1000;
pub(crate) const WINDOWS_ARM_VIRTIO_INSTALLER_ISO_MMIO_IPA: u64 =
    WINDOWS_ARM_DEVICE_MMIO_IPA + 0x2000;
pub(crate) const WINDOWS_ARM_VIRTIO_TARGET_DISK_MMIO_IPA: u64 =
    WINDOWS_ARM_DEVICE_MMIO_IPA + 0x3000;
pub(crate) const WINDOWS_ARM_GIC_DISTRIBUTOR_MMIO_IPA: u64 = WINDOWS_ARM_DEVICE_MMIO_IPA + 0x1_0000;
pub(crate) const WINDOWS_ARM_GIC_REDISTRIBUTOR_MMIO_IPA: u64 =
    WINDOWS_ARM_DEVICE_MMIO_IPA + 0x2_0000;
pub(crate) const WINDOWS_ARM_GIC_DISTRIBUTOR_BYTES: u64 = 0x1_0000;
pub(crate) const WINDOWS_ARM_GIC_REDISTRIBUTOR_BYTES: u64 = 0x2_0000;
pub(crate) const WINDOWS_ARM_GIC_PHANDLE: u32 = 1;
pub(crate) const GIC_SPI: u32 = 0;
pub(crate) const GIC_PPI: u32 = 1;
pub(crate) const IRQ_TYPE_LEVEL_HIGH: u32 = 4;
// FDT GIC SPI interrupt numbers are encoded as the global IRQ minus 32.
pub(crate) const WINDOWS_ARM_PL011_SPI: u32 = 0;
pub(crate) const WINDOWS_ARM_PL031_SPI: u32 = 1;
pub(crate) const WINDOWS_ARM_VIRTIO_INSTALLER_ISO_SPI: u32 = 2;
pub(crate) const WINDOWS_ARM_VIRTIO_TARGET_DISK_SPI: u32 = 3;
pub(crate) const WINDOWS_ARM_PL011_FLAG_VALUE: u64 = 0x90;
pub(crate) const WINDOWS_ARM_PL031_READ_VALUE: u64 = 0x2026_0618;
pub const WINDOWS_ARM_GUEST_RAM_IPA: u64 = 0x4000_0000;
pub const WINDOWS_ARM_EXECUTABLE_DIAGNOSTIC_VECTOR_IPA: u64 = 0x0020_0000;
pub const WINDOWS_ARM_DIAGNOSTIC_VECTOR_IPA: u64 = WINDOWS_ARM_UEFI_CODE_IPA;
pub const WINDOWS_ARM_GUEST_RAM_DIAGNOSTIC_VECTOR_IPA: u64 = WINDOWS_ARM_GUEST_RAM_IPA;
pub const WINDOWS_ARM_DIAGNOSTIC_VECTOR_BYTES: u64 = 0x800;
pub(crate) const WINDOWS_ARM_PLATFORM_DTB_GUEST_RAM_OFFSET: u64 = 0x0001_0000;
pub(crate) const WINDOWS_ARM_PLATFORM_DTB_IPA: u64 =
    WINDOWS_ARM_GUEST_RAM_IPA + WINDOWS_ARM_PLATFORM_DTB_GUEST_RAM_OFFSET;
pub(crate) const WINDOWS_ARM_FIRMWARE_RUN_LOOP_FDT_VCPU_COUNT: u8 = 1;
pub(crate) const WINDOWS_ARM_DIAGNOSTIC_VECTOR_CURRENT_EL_SPX_SYNC_OFFSET: usize = 0x200;
pub(crate) const AARCH64_STAGE1_PAGE_OUTPUT_ADDRESS_MASK: u64 = 0x0000_ffff_ffff_f000;
pub(crate) const WINDOWS_ARM_LOW_VECTOR_DIAGNOSTIC_PAGE_DESCRIPTOR: u64 = 0xf8f;
pub(crate) const AARCH64_HVC_0_INSTRUCTION: u32 = 0xd400_0002;
pub(crate) const AARCH64_HVC_1_INSTRUCTION: u32 = 0xd400_0022;
pub(crate) const AARCH64_ERET_INSTRUCTION: u32 = 0xd69f_03e0;
pub(crate) const WINDOWS_ARM_PLATFORM_DESCRIPTION_DEFAULT_GUEST_RAM_BYTES: u64 =
    6 * 1024 * 1024 * 1024;
pub(crate) const WINDOWS_ARM_PLATFORM_DESCRIPTION_DEFAULT_VCPU_COUNT: u8 = 4;
pub(crate) const FDT_MAGIC: u32 = 0xd00d_feed;
pub(crate) const FDT_BEGIN_NODE: u32 = 1;
pub(crate) const FDT_END_NODE: u32 = 2;
pub(crate) const FDT_PROP: u32 = 3;
pub(crate) const FDT_END: u32 = 9;

#[cfg(test)]
#[path = "constants_tests/mod.rs"]
mod tests;
