//! Split out of windows_arm.rs by responsibility.

use super::*;
use crate::*;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WindowsArmUefiFirmwareRunLoopProbe {
    pub allowed: bool,
    pub attempted: bool,
    pub vm_created: bool,
    pub firmware_memory_allocated: bool,
    pub vars_memory_allocated: bool,
    pub guest_ram_memory_allocated: bool,
    pub firmware_memory_populated: bool,
    pub vars_memory_populated: bool,
    pub firmware_memory_mapped: bool,
    pub vars_memory_mapped: bool,
    pub low_firmware_alias_mapped: bool,
    pub low_vars_alias_mapped: bool,
    pub guest_ram_memory_mapped: bool,
    pub platform_dtb_populated: bool,
    pub diagnostic_vector_seed_requested: bool,
    pub diagnostic_vector_populated: bool,
    pub low_vector_diagnostic_page_repair_requested: bool,
    pub low_vector_diagnostic_page_repaired: bool,
    pub low_vector_diagnostic_page_slot_restored: bool,
    pub low_vector_diagnostic_page_restore_before_eret_requested: bool,
    pub low_vector_diagnostic_page_restore_before_eret_attempted: bool,
    pub low_vector_diagnostic_page_entry_ipa: Option<u64>,
    pub low_vector_diagnostic_page_previous_descriptor: Option<u64>,
    pub low_vector_diagnostic_page_descriptor: Option<u64>,
    pub low_vector_diagnostic_page_repeated_fault_observed: bool,
    pub low_vector_recommended_vector_remap_requested: bool,
    pub low_vector_recommended_vector_remap_attempted: bool,
    pub low_vector_recommended_vector_remap_succeeded: bool,
    pub low_vector_recommended_vector_remap_target_physical_address: Option<u64>,
    pub low_vector_recommended_vector_remap_descriptor: Option<u64>,
    pub low_vector_post_repair_continue_requested: bool,
    pub low_vector_post_repair_continue_attempted: bool,
    pub stop_at_first_post_repair_device_boundary_requested: bool,
    pub low_vector_post_repair_unsupported_exit_observed: bool,
    pub low_vector_post_repair_unsupported_exit_reason: Option<u32>,
    pub low_vector_post_repair_unsupported_exit_diagnosis: &'static str,
    pub low_vector_post_repair_first_exit_observed: bool,
    pub low_vector_post_repair_first_exit_index: Option<u32>,
    pub low_vector_post_repair_first_exit_reason: Option<u32>,
    pub low_vector_post_repair_first_exit_diagnosis: &'static str,
    pub low_vector_post_repair_first_exit_pc: Option<u64>,
    pub low_vector_post_repair_first_interaction_kind: &'static str,
    pub low_vector_post_repair_first_exit_access_kind: &'static str,
    pub low_vector_post_repair_first_exit_access_direction: &'static str,
    pub low_vector_post_repair_first_exit_access_address: Option<u64>,
    pub low_vector_post_repair_first_exit_access_sysreg: Option<u16>,
    pub low_vector_post_repair_first_exit_access_syndrome: Option<u64>,
    pub low_vector_post_repair_first_device_interaction_observed: bool,
    pub low_vector_post_repair_first_device_interaction_index: Option<u32>,
    pub low_vector_post_repair_first_device_interaction_reason: Option<u32>,
    pub low_vector_post_repair_first_device_interaction_diagnosis: &'static str,
    pub low_vector_post_repair_first_device_interaction_pc: Option<u64>,
    pub low_vector_post_repair_first_device_interaction_kind: &'static str,
    pub low_vector_post_repair_first_device_interaction_access_kind: &'static str,
    pub low_vector_post_repair_first_device_interaction_access_direction: &'static str,
    pub low_vector_post_repair_first_device_interaction_access_address: Option<u64>,
    pub low_vector_post_repair_first_device_interaction_access_sysreg: Option<u16>,
    pub low_vector_post_repair_first_device_interaction_access_syndrome: Option<u64>,
    pub low_vector_post_repair_first_unhandled_access_observed: bool,
    pub low_vector_post_repair_first_unhandled_access_index: Option<u32>,
    pub low_vector_post_repair_first_unhandled_access_reason: Option<u32>,
    pub low_vector_post_repair_first_unhandled_access_diagnosis: &'static str,
    pub low_vector_post_repair_first_unhandled_access_pc: Option<u64>,
    pub low_vector_post_repair_first_unhandled_access_syndrome: Option<u64>,
    pub low_vector_post_repair_first_unhandled_access_kind: &'static str,
    pub low_vector_post_repair_first_unhandled_access_direction: &'static str,
    pub low_vector_post_repair_first_unhandled_access_register: Option<u8>,
    pub low_vector_post_repair_first_unhandled_access_value: Option<u64>,
    pub low_vector_post_repair_first_unhandled_access_handler_result: &'static str,
    pub low_vector_post_repair_first_unhandled_access_mmio_ipa: Option<u64>,
    pub low_vector_post_repair_first_unhandled_access_mmio_width: Option<u8>,
    pub low_vector_post_repair_first_unhandled_access_mmio_device_kind: &'static str,
    pub low_vector_post_repair_first_unhandled_access_sysreg: Option<u16>,
    pub low_vector_post_repair_first_unhandled_access_sysreg_name: &'static str,
    pub low_vector_post_repair_first_unhandled_access_sysreg_op0: Option<u8>,
    pub low_vector_post_repair_first_unhandled_access_sysreg_op1: Option<u8>,
    pub low_vector_post_repair_first_unhandled_access_sysreg_crn: Option<u8>,
    pub low_vector_post_repair_first_unhandled_access_sysreg_crm: Option<u8>,
    pub low_vector_post_repair_first_unhandled_access_sysreg_op2: Option<u8>,
    pub low_vector_diagnostic_page_resume_attempted: bool,
    pub low_vector_diagnostic_page_resume_armed: bool,
    pub low_vector_diagnostic_page_resume_original_pc: Option<u64>,
    pub low_vector_diagnostic_page_resume_original_elr_el1: Option<u64>,
    pub low_vector_diagnostic_page_resume_original_esr_el1: Option<u64>,
    pub low_vector_diagnostic_page_resume_original_far_el1: Option<u64>,
    pub low_vector_diagnostic_page_resume_original_spsr_el1: Option<u64>,
    pub low_vector_diagnostic_page_original_slot_bytes: Option<[u8; 12]>,
    pub low_vector_diagnostic_page_resume_target_instruction_before_eret: Option<u32>,
    pub low_vector_diagnostic_page_resume_target_stage1_leaf_descriptor_before_eret: Option<u64>,
    pub low_vector_diagnostic_page_resume_target_stage1_leaf_kind_before_eret: &'static str,
    pub low_vector_diagnostic_page_resume_target_is_installed_diagnostic_hvc_before_eret: bool,
    pub low_vector_diagnostic_page_resume_elr_el1_set_status: Option<i32>,
    pub low_vector_diagnostic_page_resume_spsr_el1_set_status: Option<i32>,
    pub low_vector_diagnostic_page_resume_cpsr_set_status: Option<i32>,
    pub low_vector_diagnostic_page_resume_pc_set_status: Option<i32>,
    pub vcpu_created: bool,
    pub pc_set: bool,
    pub x0_dtb_ipa_set: bool,
    pub cpsr_set: bool,
    pub sp_el1_set: bool,
    pub diagnostic_vector_vbar_el1_set: bool,
    pub recommended_vector_base_vbar_requested: bool,
    pub recommended_vector_base_vbar_attempted: bool,
    pub recommended_vector_base_vbar_set: bool,
    pub recommended_vector_base_vbar_diagnostic_vector_populated: bool,
    pub recommended_vector_base_vbar_resume_requested: bool,
    pub recommended_vector_base_vbar_resume_attempted: bool,
    pub recommended_vector_base_vbar_resume_armed: bool,
    pub interrupt_timer_wiring_requested: bool,
    pub interrupt_timer_initialized: bool,
    pub run_loop_attempted: bool,
    pub firmware_progress_observed: bool,
    pub unsupported_exit_observed: bool,
    pub watchdog_cancel_fired: bool,
    pub vcpu_destroyed: bool,
    pub firmware_memory_unmapped: bool,
    pub vars_memory_unmapped: bool,
    pub guest_ram_memory_unmapped: bool,
    pub firmware_memory_deallocated: bool,
    pub vars_memory_deallocated: bool,
    pub guest_ram_memory_deallocated: bool,
    pub vm_destroyed: bool,
    pub host: HvfHostCapabilities,
    pub pflash_map_verified: bool,
    pub reset_vector_ipa: u64,
    pub firmware_slot_ipa: u64,
    pub vars_slot_ipa: u64,
    pub low_firmware_alias_ipa: u64,
    pub low_vars_alias_ipa: u64,
    pub guest_ram_ipa: u64,
    pub platform_dtb_ipa: u64,
    pub platform_dtb_guest_ram_offset: u64,
    pub sp_el1_seed_ipa: u64,
    pub diagnostic_vector_location: &'static str,
    pub diagnostic_vector_ipa: u64,
    pub diagnostic_vector_bytes: u64,
    pub recommended_vector_base_vbar_source_exit_index: Option<u32>,
    pub recommended_vector_base_vbar_target: Option<u64>,
    pub recommended_vector_base_vbar_target_physical_address: Option<u64>,
    pub recommended_vector_base_vbar_reason: &'static str,
    pub recommended_vector_base_vbar_current_el_spx_sync_instruction_word: Option<u32>,
    pub recommended_vector_base_vbar_current_el_spx_sync_instruction_hint: &'static str,
    pub recommended_vector_base_vbar_followup_exit_observed: bool,
    pub recommended_vector_base_vbar_followup_exit_index: Option<u32>,
    pub recommended_vector_base_vbar_followup_exit_reason: Option<u32>,
    pub recommended_vector_base_vbar_followup_exit_diagnosis: &'static str,
    pub recommended_vector_base_vbar_followup_pc: Option<u64>,
    pub recommended_vector_base_vbar_followup_vbar_el1: Option<u64>,
    pub recommended_vector_base_vbar_followup_target_still_set: bool,
    pub recommended_vector_base_vbar_resume_original_pc: Option<u64>,
    pub recommended_vector_base_vbar_resume_original_elr_el1: Option<u64>,
    pub recommended_vector_base_vbar_resume_original_esr_el1: Option<u64>,
    pub recommended_vector_base_vbar_resume_original_far_el1: Option<u64>,
    pub recommended_vector_base_vbar_resume_original_spsr_el1: Option<u64>,
    pub slot_bytes: u64,
    pub guest_ram_bytes: u64,
    pub platform_dtb_bytes: usize,
    pub platform_dtb_magic: u32,
    pub platform_dtb_magic_verified: bool,
    pub requested_exits: u32,
    pub observed_exits: u32,
    pub watchdog_timeout_ms: u64,
    pub vtimer_offset_value: Option<u64>,
    pub cntv_cval_value: Option<u64>,
    pub cntv_ctl_value: Option<u64>,
    pub vtimer_exit_count: u32,
    pub pending_irq_injected_count: u32,
    pub device_irq_injected_count: u32,
    pub device_irq_cleared_count: u32,
    pub handled_mmio_read_count: u32,
    pub handled_mmio_write_count: u32,
    pub handled_pl011_mmio_count: u32,
    pub handled_pl031_mmio_count: u32,
    pub handled_gicd_mmio_count: u32,
    pub handled_gicr_mmio_count: u32,
    pub handled_virtio_installer_iso_mmio_count: u32,
    pub handled_virtio_target_disk_mmio_count: u32,
    pub virtio_queue_notify_count: u32,
    pub virtio_request_completion_count: u32,
    pub handled_icc_read_count: u32,
    pub handled_icc_write_count: u32,
    pub handled_icc_iar1_read_count: u32,
    pub handled_icc_eoir1_write_count: u32,
    pub handled_icc_dir_write_count: u32,
    pub last_icc_iar1_intid: Option<u32>,
    pub last_icc_eoir1_intid: Option<u32>,
    pub last_icc_dir_intid: Option<u32>,
    pub firmware_source_bytes: Option<u64>,
    pub vars_source_bytes: Option<u64>,
    pub installer_iso_path: Option<PathBuf>,
    pub writable_target_disk_path: Option<PathBuf>,
    pub block_devices: Vec<WindowsArmVirtioBlockDeviceMetadata>,
    pub firmware_map_flags: &'static str,
    pub vars_map_flags: &'static str,
    pub low_firmware_alias_map_flags: &'static str,
    pub low_vars_alias_map_flags: &'static str,
    pub guest_ram_map_flags: &'static str,
    pub low_pflash_alias_requested: bool,
    pub vm_create_status: Option<i32>,
    pub firmware_allocate_status: Option<i32>,
    pub vars_allocate_status: Option<i32>,
    pub guest_ram_allocate_status: Option<i32>,
    pub firmware_map_status: Option<i32>,
    pub vars_map_status: Option<i32>,
    pub low_firmware_alias_map_status: Option<i32>,
    pub low_vars_alias_map_status: Option<i32>,
    pub guest_ram_map_status: Option<i32>,
    pub vcpu_create_status: Option<i32>,
    pub pc_set_status: Option<i32>,
    pub x0_dtb_ipa_set_status: Option<i32>,
    pub cpsr_set_status: Option<i32>,
    pub sp_el1_set_status: Option<i32>,
    pub diagnostic_vector_vbar_el1_set_status: Option<i32>,
    pub recommended_vector_base_vbar_set_status: Option<i32>,
    pub recommended_vector_base_vbar_resume_vbar_el1_set_status: Option<i32>,
    pub recommended_vector_base_vbar_resume_elr_el1_set_status: Option<i32>,
    pub recommended_vector_base_vbar_resume_spsr_el1_set_status: Option<i32>,
    pub recommended_vector_base_vbar_resume_pc_set_status: Option<i32>,
    pub vtimer_offset_set_status: Option<i32>,
    pub cntv_cval_set_status: Option<i32>,
    pub cntv_ctl_set_status: Option<i32>,
    pub vtimer_initial_unmask_status: Option<i32>,
    pub last_pending_irq_set_status: Option<i32>,
    pub last_device_irq_set_status: Option<i32>,
    pub last_device_irq_clear_status: Option<i32>,
    pub last_vtimer_unmask_status: Option<i32>,
    pub final_pc_status: Option<i32>,
    pub final_pc: Option<u64>,
    pub vcpu_destroy_status: Option<i32>,
    pub firmware_unmap_status: Option<i32>,
    pub vars_unmap_status: Option<i32>,
    pub low_firmware_alias_unmap_status: Option<i32>,
    pub low_vars_alias_unmap_status: Option<i32>,
    pub guest_ram_unmap_status: Option<i32>,
    pub firmware_deallocate_status: Option<i32>,
    pub vars_deallocate_status: Option<i32>,
    pub guest_ram_deallocate_status: Option<i32>,
    pub vm_destroy_status: Option<i32>,
    pub exits: Vec<WindowsArmUefiFirmwareRunLoopExit>,
    pub blockers: Vec<String>,
}
