/** @file
  Call identifiers for the BridgeVM boot-services trace ring.
  SPDX-License-Identifier: Apache-2.0
**/
#ifndef BRIDGE_VM_PC_BOOT_SERVICE_CALLS_H_
#define BRIDGE_VM_PC_BOOT_SERVICE_CALLS_H_

#define BRIDGE_VM_PC_BS_CALL_HANDLE_PROTOCOL      1U
#define BRIDGE_VM_PC_BS_CALL_OPEN_PROTOCOL        2U
#define BRIDGE_VM_PC_BS_CALL_LOCATE_PROTOCOL      3U
#define BRIDGE_VM_PC_BS_CALL_LOCATE_HANDLE_BUFFER 4U
#define BRIDGE_VM_PC_BS_CALL_LOCATE_HANDLE        5U
#define BRIDGE_VM_PC_BS_CALL_GET_MEMORY_MAP       6U
#define BRIDGE_VM_PC_BS_CALL_ALLOCATE_PAGES       7U
#define BRIDGE_VM_PC_BS_CALL_ALLOCATE_POOL        8U
#define BRIDGE_VM_PC_BS_CALL_EXIT                 9U
#define BRIDGE_VM_PC_BS_CALL_SET_WATCHDOG_TIMER   10U
#define BRIDGE_VM_PC_BS_CALL_EXIT_BOOT_SERVICES   11U
#define BRIDGE_VM_PC_BS_CALL_GET_VARIABLE         12U
#define BRIDGE_VM_PC_BS_CALL_RAISE_TPL            13U
#define BRIDGE_VM_PC_BS_CALL_RESTORE_TPL          14U
#define BRIDGE_VM_PC_BS_CALL_CREATE_EVENT         15U
#define BRIDGE_VM_PC_BS_CALL_STALL                16U
#define BRIDGE_VM_PC_BS_CALL_SET_MEM              17U
#define BRIDGE_VM_PC_BS_CALL_COPY_MEM             18U
#define BRIDGE_VM_PC_BS_CALL_INSTALL_CONFIG_TABLE 19U

#endif
