//! Split out of mmio.rs by responsibility.

use super::super::super::*;
use super::*;
use crate::*;

pub fn probe_hvf_mmio_serial_device(
    allow_device: bool,
    host: HvfHostCapabilities,
) -> HvfMmioSerialDeviceProbe {
    HvfMmioSerialDeviceProbe {
        allowed: allow_device,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        write_value_register_set: false,
        data_address_register_set: false,
        status_address_register_set: false,
        device_bus_created: false,
        device_bus_device_count: 0,
        write_run_attempted: false,
        write_exit_observed: false,
        write_handled_by_device: false,
        write_value_captured: false,
        pc_advanced_after_write: false,
        status_run_attempted: false,
        status_exit_observed: false,
        status_handled_by_device: false,
        status_value_injected: false,
        pc_advanced_after_status: false,
        continuation_run_attempted: false,
        continuation_exit_observed: false,
        status_value_preserved: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        code_ipa_start: 0x4000_0000,
        data_ipa: 0x5000_0000,
        status_ipa: 0x5000_0018,
        bytes: 16 * 1024,
        instructions: "STR X0, [X1]; LDR X0, [X2]; HVC #0",
        serial_write_value: 0x41,
        serial_status_value: 0x90,
        captured_write_value: None,
        captured_byte: None,
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        write_value_register_set_status: None,
        data_address_register_set_status: None,
        status_address_register_set_status: None,
        write_run_status: None,
        write_exit_reason: None,
        write_exit_syndrome: None,
        write_exit_virtual_address: None,
        write_exit_physical_address: None,
        write_watchdog_cancel_status: None,
        write_value_capture_status: None,
        pc_read_after_write_status: None,
        pc_after_write_exit: None,
        pc_advance_after_write_status: None,
        status_run_status: None,
        status_exit_reason: None,
        status_exit_syndrome: None,
        status_exit_virtual_address: None,
        status_exit_physical_address: None,
        status_watchdog_cancel_status: None,
        status_value_set_status: None,
        pc_read_after_status_status: None,
        pc_after_status_exit: None,
        pc_advance_after_status_status: None,
        continuation_run_status: None,
        continuation_exit_reason: None,
        continuation_exit_syndrome: None,
        continuation_exit_virtual_address: None,
        continuation_exit_physical_address: None,
        continuation_watchdog_cancel_status: None,
        status_value_after_continue_status: None,
        status_value_after_continue: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework MMIO serial device probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_mmio_rtc_device(
    allow_device: bool,
    host: HvfHostCapabilities,
) -> HvfMmioRtcDeviceProbe {
    HvfMmioRtcDeviceProbe {
        allowed: allow_device,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        rtc_address_register_set: false,
        device_bus_created: false,
        device_bus_device_count: 0,
        first_run_attempted: false,
        rtc_exit_observed: false,
        rtc_handled_by_device: false,
        rtc_value_injected: false,
        pc_read_after_rtc_exit: false,
        pc_advanced: false,
        second_run_attempted: false,
        continuation_exit_observed: false,
        rtc_value_preserved: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        device_models: BOOT_MMIO_DEVICE_MODELS,
        code_ipa_start: 0x4000_0000,
        uart_ipa: 0x5000_0000,
        rtc_ipa: 0x5000_1000,
        bytes: 16 * 1024,
        instructions: "LDR X0, [X1]; HVC #0",
        rtc_value: 0x2026_0618,
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        rtc_address_register_set_status: None,
        first_run_status: None,
        rtc_exit_reason: None,
        rtc_exit_syndrome: None,
        rtc_exit_virtual_address: None,
        rtc_exit_physical_address: None,
        first_watchdog_cancel_status: None,
        rtc_value_set_status: None,
        pc_read_status: None,
        pc_after_rtc_exit: None,
        pc_advance_status: None,
        second_run_status: None,
        continuation_exit_reason: None,
        continuation_exit_syndrome: None,
        continuation_exit_virtual_address: None,
        continuation_exit_physical_address: None,
        second_watchdog_cancel_status: None,
        rtc_value_after_continue_status: None,
        rtc_value_after_continue: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework MMIO RTC device probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_mmio_block_device(
    allow_device: bool,
    host: HvfHostCapabilities,
) -> HvfMmioBlockDeviceProbe {
    HvfMmioBlockDeviceProbe {
        allowed: allow_device,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        register_address_registers_set: false,
        device_bus_created: false,
        device_bus_device_count: 0,
        register_reads: unsupported_block_register_reads(),
        continuation_run_attempted: false,
        continuation_exit_observed: false,
        vendor_value_preserved: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        device_models: BOOT_MMIO_DEVICE_MODELS,
        code_ipa_start: 0x4000_0000,
        block_ipa: 0x5000_2000,
        bytes: 16 * 1024,
        instructions: "LDR W0 magic/version/device/vendor; HVC #0",
        magic_value: VIRTIO_MMIO_MAGIC_VALUE,
        version_value: VIRTIO_MMIO_VERSION_VALUE,
        device_id_value: VIRTIO_MMIO_BLOCK_DEVICE_ID_VALUE,
        vendor_id_value: VIRTIO_MMIO_VENDOR_ID_VALUE,
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        register_address_registers_set_status: vec![None; 4],
        continuation_run_status: None,
        continuation_exit_reason: None,
        continuation_exit_syndrome: None,
        continuation_exit_virtual_address: None,
        continuation_exit_physical_address: None,
        continuation_watchdog_cancel_status: None,
        vendor_value_after_continue_status: None,
        vendor_value_after_continue: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework MMIO block device probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_mmio_block_queue(
    allow_device: bool,
    disk_path: Option<PathBuf>,
    iso_path: Option<PathBuf>,
    writable_disk_path: Option<PathBuf>,
    host: HvfHostCapabilities,
) -> HvfMmioBlockQueueProbe {
    let (block_backing_kind, block_backing_path) = if let Some(path) = writable_disk_path {
        ("host-file-writable", Some(path))
    } else if let Some(path) = iso_path {
        ("host-iso-readonly", Some(path))
    } else if let Some(path) = disk_path {
        ("host-file", Some(path))
    } else {
        ("synthetic-sector-pattern", None)
    };
    HvfMmioBlockQueueProbe {
        allowed: allow_device,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        device_bus_created: false,
        device_bus_device_count: 0,
        steps: unsupported_block_queue_steps(),
        continuation_run_attempted: false,
        continuation_exit_observed: false,
        capacity_high_value_preserved: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        device_models: BLOCK_QUEUE_MMIO_DEVICE_MODELS,
        code_ipa_start: 0x4000_0000,
        block_ipa: 0x5000_2000,
        bytes: 16 * 1024,
        instructions: "LDR/STR W0 VirtIO-MMIO queue/config/address/notify registers; HVC #0",
        device_features_value: VIRTIO_MMIO_BLOCK_DEVICE_FEATURES_VALUE,
        driver_features_value: VIRTIO_MMIO_BLOCK_DRIVER_FEATURES_VALUE,
        queue_select_value: VIRTIO_MMIO_BLOCK_QUEUE_SEL_VALUE,
        queue_num_max_value: VIRTIO_MMIO_BLOCK_QUEUE_NUM_MAX_VALUE,
        queue_num_value: VIRTIO_MMIO_BLOCK_QUEUE_NUM_VALUE,
        queue_ready_value: VIRTIO_MMIO_BLOCK_QUEUE_READY_VALUE,
        queue_desc_address: VIRTIO_MMIO_BLOCK_QUEUE_DESC_ADDRESS,
        queue_driver_address: VIRTIO_MMIO_BLOCK_QUEUE_DRIVER_ADDRESS,
        queue_device_address: VIRTIO_MMIO_BLOCK_QUEUE_DEVICE_ADDRESS,
        queue_notify_value: VIRTIO_MMIO_BLOCK_QUEUE_NOTIFY_VALUE,
        interrupt_status_value: VIRTIO_MMIO_INTERRUPT_USED_BUFFER_VALUE,
        block_backing_kind,
        block_backing_path,
        request_ring_seeded: false,
        request_completed_after_notify: false,
        request_descriptor_index: None,
        request_sector: None,
        request_byte_offset: None,
        request_data_bytes: None,
        request_data_prefix: Vec::new(),
        request_status: None,
        request_used_index: None,
        request_used_len: None,
        request_interrupt_status: None,
        write_completed_after_notify: false,
        write_request_type: None,
        write_sector: None,
        write_byte_offset: None,
        write_data_bytes: None,
        write_data_prefix: Vec::new(),
        write_status: None,
        write_used_index: None,
        write_used_len: None,
        flush_completed_after_notify: false,
        flush_request_type: None,
        flush_status: None,
        flush_used_index: None,
        flush_used_len: None,
        persisted_data_prefix: Vec::new(),
        status_value: VIRTIO_MMIO_BLOCK_STATUS_VALUE,
        capacity_sectors: VIRTIO_MMIO_BLOCK_CAPACITY_SECTORS,
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        continuation_run_status: None,
        continuation_exit_reason: None,
        continuation_exit_syndrome: None,
        continuation_exit_virtual_address: None,
        continuation_exit_physical_address: None,
        continuation_watchdog_cancel_status: None,
        capacity_high_after_continue_status: None,
        capacity_high_after_continue: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework MMIO block queue/config/address/notify probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub(crate) fn unsupported_block_register_reads() -> Vec<HvfMmioBlockRegisterProbe> {
    [
        ("magic", 0x5000_2000, VIRTIO_MMIO_MAGIC_VALUE),
        ("version", 0x5000_2004, VIRTIO_MMIO_VERSION_VALUE),
        ("device_id", 0x5000_2008, VIRTIO_MMIO_BLOCK_DEVICE_ID_VALUE),
        ("vendor_id", 0x5000_200c, VIRTIO_MMIO_VENDOR_ID_VALUE),
    ]
    .into_iter()
    .map(|(name, ipa, expected_value)| HvfMmioBlockRegisterProbe {
        name,
        ipa,
        expected_value,
        run_attempted: false,
        exit_observed: false,
        handled_by_device: false,
        value_injected: false,
        pc_read_after_exit: false,
        pc_advanced: false,
        run_status: None,
        exit_reason: None,
        exit_syndrome: None,
        exit_virtual_address: None,
        exit_physical_address: None,
        watchdog_cancel_status: None,
        value_set_status: None,
        pc_read_status: None,
        pc_after_exit: None,
        pc_advance_status: None,
    })
    .collect()
}

pub(crate) fn unsupported_block_queue_steps() -> Vec<HvfMmioBlockQueueStepProbe> {
    [
        (
            "device_features",
            "read",
            0x5000_2010,
            Some(VIRTIO_MMIO_BLOCK_DEVICE_FEATURES_VALUE),
            None,
        ),
        (
            "driver_features",
            "write",
            0x5000_2020,
            None,
            Some(VIRTIO_MMIO_BLOCK_DRIVER_FEATURES_VALUE),
        ),
        (
            "status_ack",
            "write",
            0x5000_2070,
            None,
            Some(VIRTIO_MMIO_BLOCK_STATUS_ACK_VALUE),
        ),
        (
            "status_driver",
            "write",
            0x5000_2070,
            None,
            Some(VIRTIO_MMIO_BLOCK_STATUS_DRIVER_VALUE),
        ),
        (
            "status_features_ok",
            "write",
            0x5000_2070,
            None,
            Some(VIRTIO_MMIO_BLOCK_STATUS_FEATURES_OK_VALUE),
        ),
        (
            "queue_select",
            "write",
            0x5000_2030,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_SEL_VALUE),
        ),
        (
            "queue_num_max",
            "read",
            0x5000_2034,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_NUM_MAX_VALUE),
            None,
        ),
        (
            "queue_num",
            "write",
            0x5000_2038,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_NUM_VALUE),
        ),
        (
            "queue_desc_low",
            "write",
            0x5000_2080,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DESC_ADDRESS & 0xffff_ffff),
        ),
        (
            "queue_desc_high",
            "write",
            0x5000_2084,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DESC_ADDRESS >> 32),
        ),
        (
            "queue_driver_low",
            "write",
            0x5000_2090,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DRIVER_ADDRESS & 0xffff_ffff),
        ),
        (
            "queue_driver_high",
            "write",
            0x5000_2094,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DRIVER_ADDRESS >> 32),
        ),
        (
            "queue_device_low",
            "write",
            0x5000_20a0,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DEVICE_ADDRESS & 0xffff_ffff),
        ),
        (
            "queue_device_high",
            "write",
            0x5000_20a4,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DEVICE_ADDRESS >> 32),
        ),
        (
            "queue_ready",
            "write",
            0x5000_2044,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_READY_VALUE),
        ),
        (
            "status_driver_ok",
            "write",
            0x5000_2070,
            None,
            Some(VIRTIO_MMIO_BLOCK_STATUS_VALUE),
        ),
        (
            "status",
            "read",
            0x5000_2070,
            Some(VIRTIO_MMIO_BLOCK_STATUS_VALUE),
            None,
        ),
        (
            "queue_notify",
            "write",
            0x5000_2050,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_NOTIFY_VALUE),
        ),
        (
            "queue_ready",
            "read",
            0x5000_2044,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_READY_VALUE),
            None,
        ),
        (
            "queue_desc_low",
            "read",
            0x5000_2080,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DESC_ADDRESS & 0xffff_ffff),
            None,
        ),
        (
            "queue_driver_low",
            "read",
            0x5000_2090,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DRIVER_ADDRESS & 0xffff_ffff),
            None,
        ),
        (
            "queue_device_low",
            "read",
            0x5000_20a0,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DEVICE_ADDRESS & 0xffff_ffff),
            None,
        ),
        (
            "interrupt_status",
            "read",
            0x5000_2060,
            Some(VIRTIO_MMIO_INTERRUPT_USED_BUFFER_VALUE),
            None,
        ),
        ("config_generation", "read", 0x5000_20fc, Some(0), None),
        (
            "capacity_low",
            "read",
            0x5000_2100,
            Some(VIRTIO_MMIO_BLOCK_CAPACITY_SECTORS & 0xffff_ffff),
            None,
        ),
        (
            "capacity_high",
            "read",
            0x5000_2104,
            Some(VIRTIO_MMIO_BLOCK_CAPACITY_SECTORS >> 32),
            None,
        ),
    ]
    .into_iter()
    .map(
        |(name, access, ipa, expected_value, write_value)| HvfMmioBlockQueueStepProbe {
            name,
            access,
            ipa,
            expected_value,
            write_value,
            run_attempted: false,
            address_register_set: false,
            write_value_register_set: false,
            exit_observed: false,
            handled_by_device: false,
            value_injected: false,
            write_accepted: false,
            pc_read_after_exit: false,
            pc_advanced: false,
            captured_write_value: None,
            run_status: None,
            address_register_set_status: None,
            write_value_register_set_status: None,
            exit_reason: None,
            exit_syndrome: None,
            exit_virtual_address: None,
            exit_physical_address: None,
            watchdog_cancel_status: None,
            value_set_status: None,
            pc_read_status: None,
            pc_after_exit: None,
            pc_advance_status: None,
        },
    )
    .collect()
}
