//! Split out of mmio.rs by responsibility.

use super::super::super::*;
use super::*;
use crate::*;

pub fn probe_hvf_mmio_read_exit(
    allow_mmio: bool,
    host: HvfHostCapabilities,
) -> HvfMmioReadExitProbe {
    HvfMmioReadExitProbe {
        allowed: allow_mmio,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        address_register_set: false,
        run_attempted: false,
        mmio_exit_observed: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        device_model: PL011_UART_MODEL,
        code_ipa_start: 0x4000_0000,
        mmio_ipa: 0x5000_0000,
        bytes: 16 * 1024,
        instruction: "LDR X0, [X1]",
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        address_register_set_status: None,
        run_status: None,
        exit_reason: None,
        exit_syndrome: None,
        exit_virtual_address: None,
        exit_physical_address: None,
        watchdog_cancel_status: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework MMIO read exit probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_mmio_read_emulation(
    allow_emulate: bool,
    host: HvfHostCapabilities,
) -> HvfMmioReadEmulationProbe {
    HvfMmioReadEmulationProbe {
        allowed: allow_emulate,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        address_register_set: false,
        first_run_attempted: false,
        mmio_exit_observed: false,
        pc_read_after_mmio_exit: false,
        emulated_value_injected: false,
        pc_advanced: false,
        second_run_attempted: false,
        continuation_exit_observed: false,
        emulated_value_preserved: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        code_ipa_start: 0x4000_0000,
        mmio_ipa: 0x5000_0000,
        bytes: 16 * 1024,
        instructions: "LDR X0, [X1]; HVC #0",
        emulated_value: 0x1234_5678_9abc_def0,
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        address_register_set_status: None,
        first_run_status: None,
        mmio_exit_reason: None,
        mmio_exit_syndrome: None,
        mmio_exit_virtual_address: None,
        mmio_exit_physical_address: None,
        first_watchdog_cancel_status: None,
        pc_read_status: None,
        pc_after_mmio_exit: None,
        emulated_value_set_status: None,
        pc_advance_status: None,
        second_run_status: None,
        continuation_exit_reason: None,
        continuation_exit_syndrome: None,
        continuation_exit_virtual_address: None,
        continuation_exit_physical_address: None,
        second_watchdog_cancel_status: None,
        emulated_value_read_status: None,
        emulated_value_after_continue: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework MMIO read emulation probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_mmio_write_emulation(
    allow_emulate: bool,
    host: HvfHostCapabilities,
) -> HvfMmioWriteEmulationProbe {
    HvfMmioWriteEmulationProbe {
        allowed: allow_emulate,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        write_value_register_set: false,
        address_register_set: false,
        first_run_attempted: false,
        mmio_exit_observed: false,
        pc_read_after_mmio_exit: false,
        write_value_captured: false,
        pc_advanced: false,
        second_run_attempted: false,
        continuation_exit_observed: false,
        write_value_preserved: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        code_ipa_start: 0x4000_0000,
        mmio_ipa: 0x5000_0000,
        bytes: 16 * 1024,
        instructions: "STR X0, [X1]; HVC #0",
        write_value: 0x0fed_cba9_8765_4321,
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        write_value_register_set_status: None,
        address_register_set_status: None,
        first_run_status: None,
        mmio_exit_reason: None,
        mmio_exit_syndrome: None,
        mmio_exit_virtual_address: None,
        mmio_exit_physical_address: None,
        first_watchdog_cancel_status: None,
        pc_read_status: None,
        pc_after_mmio_exit: None,
        write_value_capture_status: None,
        captured_write_value: None,
        pc_advance_status: None,
        second_run_status: None,
        continuation_exit_reason: None,
        continuation_exit_syndrome: None,
        continuation_exit_virtual_address: None,
        continuation_exit_physical_address: None,
        second_watchdog_cancel_status: None,
        write_value_after_continue_status: None,
        write_value_after_continue: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework MMIO write emulation probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}
