//! Split out of mmio.rs by responsibility.

use super::super::super::*;
use super::*;
use crate::*;

pub fn probe_hvf_guest_entry(allow_entry: bool, host: HvfHostCapabilities) -> HvfGuestEntryProbe {
    HvfGuestEntryProbe {
        allowed: allow_entry,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        run_attempted: false,
        entry_boundary_observed: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        ipa_start: 0x4000_0000,
        bytes: 16 * 1024,
        instruction: "HVC #0",
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        run_status: None,
        exit_reason: None,
        exit_syndrome: None,
        exit_virtual_address: None,
        exit_physical_address: None,
        watchdog_cancel_status: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework guest entry probe is only available on Apple Silicon macOS"
                .to_string(),
        ],
    }
}

pub fn probe_hvf_guest_exit_loop(
    allow_loop: bool,
    host: HvfHostCapabilities,
) -> HvfGuestExitLoopProbe {
    HvfGuestExitLoopProbe {
        allowed: allow_loop,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        initial_pc_set: false,
        cpsr_set: false,
        first_run_attempted: false,
        first_exit_observed: false,
        pc_read_after_first_exit: false,
        pc_advanced: false,
        second_run_attempted: false,
        second_exit_observed: false,
        exit_loop_observed: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        ipa_start: 0x4000_0000,
        bytes: 16 * 1024,
        instructions: "HVC #0; HVC #1",
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        initial_pc_set_status: None,
        cpsr_set_status: None,
        first_run_status: None,
        first_exit_reason: None,
        first_exit_syndrome: None,
        first_exit_virtual_address: None,
        first_exit_physical_address: None,
        first_watchdog_cancel_status: None,
        pc_read_status: None,
        pc_after_first_exit: None,
        pc_advance_status: None,
        second_run_status: None,
        second_exit_reason: None,
        second_exit_syndrome: None,
        second_exit_virtual_address: None,
        second_exit_physical_address: None,
        second_watchdog_cancel_status: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework guest exit loop probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}
