#!/usr/bin/env bash
# Regenerate ../bridgevm-vulkan-draw-shaders.h from the GLSL sources.
# Requires glslang (brew install glslang).
set -euo pipefail

DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
OUT="$DIR/../bridgevm-vulkan-draw-shaders.h"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

GLSLANG=${GLSLANG:-glslang}
"$GLSLANG" --target-env vulkan1.1 -V "$DIR/bridgevm-draw.vert" -o "$TMP/vert.spv"
"$GLSLANG" --target-env vulkan1.1 -V "$DIR/bridgevm-draw.frag" -o "$TMP/frag.spv"

emit_array() {
  local name=$1 spv=$2
  python3 - "$name" "$spv" <<'PY'
import struct
import sys

name, path = sys.argv[1], sys.argv[2]
data = open(path, "rb").read()
assert len(data) % 4 == 0, path
words = struct.unpack("<%uI" % (len(data) // 4), data)
print("static const uint32_t %s[] = {" % name)
for i in range(0, len(words), 6):
    row = ", ".join("0x%08x" % w for w in words[i : i + 6])
    print("    %s," % row)
print("};")
PY
}

{
  echo "/* Generated by scripts/win-tests/shaders/gen-vulkan-draw-shaders.sh."
  echo "   Do not edit by hand; edit the GLSL sources and regenerate. */"
  echo "#pragma once"
  echo "#include <stdint.h>"
  echo
  emit_array bridgevm_draw_vert_spv "$TMP/vert.spv"
  echo
  emit_array bridgevm_draw_frag_spv "$TMP/frag.spv"
} > "$OUT"

echo "wrote $OUT"
