"""Explicitly publishable receipt keys; newly introduced keys remain private by default."""
from receipt_extended_fields import T19_FIELDS, T1_FIELDS
# Fields safe to publish. Anything absent is dropped.
ALLOWED_FIELDS = frozenset(
    {
        "probe",
        "gate_id",
        "criterion",
        "tested_commit",
        "tier",
        "job_id",
        "commit",
        "image_sha256",
        "guest_image_sha256",
        "vars_sha256",
        "driver_store_hash",
        "title_sha256",
        "ppsspp_sha256",
        "ppsspp_payload_sha256",
        "ppsspp_executable_sha256",
        "dxvk_d3d11_sha256",
        "dxvk_dxgi_sha256",
        "virglrenderer_sha256", "render_server_sha256",
        "moltenvk_sha256",
        "gate_asset_hash",
        "input_manifest_sha256",
        "started_at",
        "finished_at",
        "elapsed_ms",
        "host_model",
        "macos_version",
        "host_os",
        "host_hardware",
        "outcome",
        "pass",
        "passes",
        "failures",
        "sample_count",
        "run_count",
        "required_run_count",
        "threshold_fps",
        "module_identity_verified",
        "iterations",
        "timer_wakes",
        "canceled_exits",
        "surplus_canceled",
        "masked_past_deadline",
        "recoveries",
        "swallowed_unrecovered",
        "vtimer_exits",
        "trace_overflow",
        "boots_attempted",
        "boots_passed",
        "stage4_pass",
        "firstboot_fresh",
        "cpus_online",
        "fps_p50",
        "fps_samples",
        "evidence_paths",
        "known_confounders",
        "driver_hash",
        "image_hash", "matrix_report_sha256", "matrix_report_set_sha256", "run_log_set_sha256", "smp_configurations", "runs_per_configuration", "smp_execution_order", "desktop_samples_ms", "desktop_medians_ms", "desktop_p95_ms", "median_delta_from_4_percent", "best_smp_cpus", "best_median_desktop_ms", "pair_count", "pair_execution_order", "four_vcpu_samples_ms", "six_vcpu_samples_ms", "four_vcpu_p50_ms", "six_vcpu_p50_ms", "four_vcpu_p95_ms", "six_vcpu_p95_ms", "paired_delta_percent", "paired_median_delta_percent", "paired_median_delta_percent_ci95", "aa_noise_upper_percent", "decision_conditions", "product_default_candidate_worth_implementing",
        "vars_hash",
        "binary_hash", "injector_sha256", "agent_sha256", "prepared_image_sha256", "prepared_vars_sha256", "injector_boot_observed", "f1_driver_load", "f2_resize", "f3_window_verbs", "f4_glyph_observation", "active_scanout_capture", "landed", "pointer_sample_count", "rendering_package_regressions", "p95_first_changed_ms", "baseline_iterations", "baseline_matches", "load_processes", "desktop_elapsed_ms", "smp_cpus", "ram_mib", "power_source", "caffeinated", "security_services_enabled", "thermal_state", "post_clone_cooldown_seconds", "guest_settle_seconds", "config_sha256", "valid", "invalid_reason", "schema_version", "harness_commit", "binary_source_commit", "binary_profile", "binary_features", "rust_toolchain", "firmware_sha256", "renderer_sha256", "workload_profile", "power_source_start", "power_source_end", "power_log_sha256", "campaign_registry_sha256", "public_seed_sha256", "environment_policy_sha256", "environment_helper_sha256", "pmset_policy_sha256", "thermal_log_sha256", "hid_log_sha256", "guest_quiescence_script_sha256", "guest_quiescence_config_sha256", "guest_quiescence_log_sha256", "campaign_id", "campaign_mode", "campaign_role", "campaign_label", "campaign_order", "campaign_pair", "campaign_ordinal", "campaign_expected_runs", "workload_script_sha256", "raw_sha256", "result_sha256", "done_sha256", "warmup_sha256", "post_read_sha256", "final_sha256", "nonce", "file_mib", "transfer_kib", "read_passes", "write_passes", "queue_depth", "post_warmup_settle_seconds", "post_warmup_settle_ms", "verification_timing", "replacement_policy", "optional_stopping", "file_bytes", "transfer_bytes", "blocks_per_pass", "precondition_write_ops", "precondition_write_bytes", "warmup_read_ops", "warmup_read_bytes", "measured_read_ops", "measured_read_bytes", "post_read_verify_ops", "post_read_verify_bytes", "measured_write_ops", "measured_write_bytes", "write_verify_read_ops", "write_verify_read_bytes", "read_result_count", "write_result_count", "final_verify_read_ops", "final_verify_read_bytes", "verified_read_ops", "flush_calls", "bytes_per_sector", "file_alignment_bytes", "required_alignment_bytes", "read_phase_elapsed_ns", "read_service_elapsed_ns", "read_pass_elapsed_count", "write_phase_elapsed_ns", "write_and_flush_service_elapsed_ns", "read_phase_mib_per_sec", "read_service_mib_per_sec", "read_throughput_mib_s", "read_p50_ms", "read_p95_ms", "read_p99_ms", "read_max_ms", "read_pass_p50_ms", "read_pass_p95_ms", "read_pass_p99_ms", "read_pass_max_ms", "write_durable_mib_per_sec", "write_and_flush_service_mib_per_sec", "write_durable_throughput_mib_s", "write_p50_ms", "write_p95_ms", "write_p99_ms", "write_max_ms", "flush_p50_ms", "flush_p95_ms", "flush_p99_ms", "flush_max_ms", "thermal_sample_count", "thermal_nominal_samples", "host_hid_idle_start_seconds", "host_hid_idle_end_seconds", "host_hid_reset_count", "guest_quiescence_sample_count", "guest_cpu_median_percent", "guest_cpu_p95_percent", "guest_disk_bps_median", "guest_disk_bps_p95", "guest_disk_queue_p95", "hosted_ci_commit", "artifact_signing_class", "expected_runs", "failure_code", "claim_eligible", "criterion_pass", "capability_promotion", "clean_machine", "ui_frontend_automated", "product_model_automated", "three_d_injection", "worker_cleanup_verified", "app_profile", "pair_bytes", "rejected_quota_bytes", "accepted_quota_bytes", "refusal_exit_code", "refusal_reason", "refusal_destination_absent", "success_verified", "quota_case_count", "refusal_output_sha256", "snapshot_manifest_sha256", "snapshot_disk_sha256", "snapshot_vars_sha256",  "hosted_ci_green", "security_ci_green", "hosted_ci_run_id", "security_ci_run_id", "app_artifact_sha256", "app_cli_sha256", "app_executable_sha256", "helper_sha256", "snapshot_helper_sha256", "runner_sha256", "secure_boot_policy_sha256", "iso_sha256", "installer_source_sha256", "bundled_vars_seed_sha256", "final_disk_sha256", "final_vars_sha256", "snapshot_create_result_sha256", "snapshot_restore_result_sha256", "snapshot_export_result_sha256", "snapshot_export_manifest_sha256", "exported_disk_sha256", "exported_vars_sha256", "original_marker_sha256", "clobber_marker_sha256", "restored_marker_sha256", "natural_shutdown_count", "secure_boot_receipt_sha256", "guest_evidence_sha256", "artifact_preflight_passes", "vm_created_passes", "source_prepared_passes", "windows_installed_passes", "secure_boot_provisioned_passes", "first_ready_passes", "keyboard_pointer_passes", "clipboard_passes", "folder_share_passes", "network_passes", "audio_passes", "first_shutdown_passes", "snapshot_restore_passes", "second_ready_passes", "second_shutdown_passes",
        "final_prepared_image_sha256", "final_prepared_vars_sha256", "snapshot_restore_retry_result_sha256", "preinterrupt_disk_sha256", "preinterrupt_vars_sha256", "postkill_disk_sha256", "postkill_vars_sha256", "postretry_disk_sha256", "postretry_vars_sha256", "postkill_export_result_sha256", "postkill_export_manifest_sha256", "postretry_export_result_sha256", "postretry_export_manifest_sha256", "postkill_marker_sha256", "stop_fd_log_sha256", "helper_stop_verified", "staged_file_sync_order_verified", "old_selection_before_kill", "helper_killed_and_reaped", "postkill_pair_unchanged", "postretry_original_restored", "interruption_case_count", "interruption_stage", "swap_interruption_stage", "swap_stop_fd_log_sha256", "swap_helper_stop_verified", "swap_staged_file_sync_order_verified", "swap_old_selection_before_kill", "swap_helper_killed_and_reaped", "swap_selection_unchanged_after_kill", "swap_retry_succeeded", "create_interruption_stage", "create_stop_fd_log_sha256", "create_helper_stop_verified", "create_staged_file_sync_order_verified", "create_old_selection_before_kill", "create_helper_killed_and_reaped", "create_selection_unchanged_after_kill", "create_retry_succeeded", "swap_preinterrupt_disk_sha256", "swap_preinterrupt_vars_sha256", "swap_postkill_disk_sha256", "swap_postkill_vars_sha256", "swap_retry_result_sha256", "swap_postretry_disk_sha256", "swap_postretry_vars_sha256", "create_source_disk_sha256", "create_source_vars_sha256", "create_preinterrupt_manifest_sha256", "create_postkill_manifest_sha256", "create_retry_result_sha256", "create_postretry_manifest_sha256", "create_postretry_disk_sha256", "create_postretry_vars_sha256", "lane_ordinals", "lane_pass", "lane_cleanup_verified", "lane_boots_attempted", "lane_boots_passed", "lane_natural_shutdown_counts", "lane_prepared_image_sha256", "lane_prepared_vars_sha256", "lane_exported_disk_sha256", "lane_exported_vars_sha256", "lane_final_disk_sha256", "lane_final_vars_sha256", "lane_original_marker_sha256", "lane_clobber_marker_sha256", "lane_restored_marker_sha256", "lane_record_sha256",
    }
) | T19_FIELDS | T1_FIELDS
