#!/usr/bin/env python3
"""Generic directory/tar import independence through real CLI and daemon APIs.

All disks contain only generated byte patterns. No VM or guest workload runs.
Real QEMU tools are mandatory, including on hosted deterministic runners.
"""
from __future__ import annotations

import json
from pathlib import Path
import tempfile
import unittest

from bundle_import_portability_support import (
    DISK_SNAPSHOTS, NAME, binaries, daemon, digests, endpoint, export_metadata, io,
    payload_digest, read_json, refuse, request, required_qemu, run, source_fixture,
)


class BundleImportPortability(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.qemu_img, cls.qemu_io = required_qemu()
        cls.cli, cls.daemon_binary = binaries()

    def check_chain(self, bundle: Path, selected: Path):
        info = json.loads(run(self.qemu_img, "info", "--output=json",
                              "--backing-chain", selected))
        self.assertEqual(len(info), 4)
        for image in info:
            self.assertEqual(image["format"], "qcow2")
            self.assertEqual(image["virtual-size"], 8 * 1024 * 1024)
            self.assertTrue(Path(image["filename"]).resolve().is_relative_to(bundle))
            if "full-backing-filename" in image:
                self.assertTrue(Path(image["full-backing-filename"]).resolve()
                                .is_relative_to(bundle))
        for index in range(4):
            io(self.qemu_io, selected, "read", 17 * (index + 1), 4096 * index)

    def preserved(self, source: Path, bundle: Path, original: dict, name: str,
                  renamed: bool, share: Path, export_receipt: dict, input_path: Path):
        for relative in ("metadata/snapshots.json", "metadata/state.json",
                         "metadata/guest-tools-token.json", "metadata/machine-identifier.bin",
                         "metadata/network-mac-address.txt", "metadata/retained-evidence.json"):
            self.assertEqual(digests(bundle)[relative], original[relative], relative)
        manifest = (bundle / "manifest.yaml").read_text()
        self.assertIn(f"name: {name}\n", manifest)
        self.assertIn(f"hostname: {name}.bridgevm.local\n", manifest)
        self.assertIn("fixture-share-token", manifest)
        self.assertIn("2222", manifest)
        self.assertIn(str(share), manifest)
        receipt = read_json(bundle / "metadata/import.json")
        self.assertEqual(receipt["original_name"], NAME)
        self.assertEqual(receipt["vm"], name)
        self.assertEqual(receipt.get("requested_name"), name if renamed else None)
        self.assertEqual(receipt["manifest_identity_rewritten"], renamed)
        self.assertTrue(receipt["manifest_preserved"])
        self.assertTrue(receipt["metadata_preserved"])
        self.assertEqual(receipt["archive_format"], export_receipt["archive_format"])
        self.assertEqual(Path(receipt["source"]), input_path)
        self.assertEqual(Path(receipt["output"]), bundle)
        self.assertEqual(receipt["copied_file_count"], len(receipt["copied_files"]))
        self.assertFalse(any(Path(entry).is_absolute() for entry in receipt["copied_files"]))
        self.assertFalse(any(path.suffix in (".sock", ".lock") for path in bundle.rglob("*")))
        self.assertEqual(read_json(bundle / "metadata/export.json"), export_receipt)
        catalog = read_json(bundle / "metadata/snapshots.json")
        self.assertEqual({entry["name"] for entry in catalog},
                         {*DISK_SNAPSHOTS, "sleep point"})
        suspend = read_json(bundle / "metadata/suspend-images/sleep-point.json")
        self.assertEqual(Path(suspend["image_path"]).read_bytes(),
                         b"synthetic suspend fixture; no guest state")
        self.assertTrue(Path(suspend["image_path"]).is_relative_to(bundle))
        for relative in ("legacy-snapshot-create.json", "creates/base.json",
                         "creates/base-create.json"):
            path = Path("metadata/snapshot-disks") / relative
            before, after = read_json(source / path), read_json(bundle / path)
            for field in ("snapshot", "executed", "exit_status", "stdout", "stderr",
                          "created_at_unix", "command"):
                self.assertEqual(after[field], before[field], f"{relative}: {field}")
            self.assertTrue(Path(after["disk"]["overlay_path"]).is_relative_to(bundle))
            self.assertTrue(Path(after["disk"]["backing_path"]).is_relative_to(bundle))

    def scenario(self, archive: str, renamed: bool):
        with tempfile.TemporaryDirectory(prefix="bridgevm-portable-", dir="/tmp") as temporary:
            root = Path(temporary).resolve()
            bundle, original = source_fixture(root, self.cli, self.qemu_img, self.qemu_io)
            source = bundle.parents[1]
            export = root / ("exported bundle.tar" if archive == "tar" else "exported bundle.vmbridge")
            endpoint(self.cli, store=source)("export", NAME, "--output", export)
            exported_metadata = export_metadata(export)
            self.assertEqual(Path(exported_metadata["source"]), bundle)
            self.assertEqual(Path(exported_metadata["output"]), export)
            self.assertEqual(exported_metadata["archive_format"], archive)
            # Import the relocated payload while both original paths are absent.
            hidden_source = root / "withdrawn source"
            source.rename(hidden_source)
            relocated_export = root / ("relocated payload.tar" if archive == "tar" else "relocated payload.vmbridge")
            export.rename(relocated_export)
            input_digest = payload_digest(relocated_export)
            self.assertFalse(source.exists())
            self.assertFalse(export.exists())
            preserved_source = hidden_source / f"vms/{NAME}.vmbridge"
            targets = (root / "local target", root / "socket target")
            name = "renamed-copy" if renamed else NAME
            extra = ("--name", name) if renamed else ()
            local = endpoint(self.cli, store=targets[0])
            with daemon(self.daemon_binary, targets[1]) as sock:
                remote = endpoint(self.cli, sock=sock)
                for call in (local, remote):
                    self.assertIn(f"Imported {name}", call("import", relocated_export, *extra))
                    self.assertEqual(payload_digest(relocated_export), input_digest)
                self.assertEqual(digests(preserved_source), original)
                # Retain hashes/evidence while making every original path unavailable.
                hidden_export = root / "withdrawn export"
                relocated_export.rename(hidden_export)
                self.assertFalse(relocated_export.exists())
                imports = tuple(target / f"vms/{name}.vmbridge" for target in targets)
                for imported, call in zip(imports, (local, remote)):
                    self.preserved(preserved_source, imported, original, name, renamed,
                                   root / "approved workspace", exported_metadata, relocated_export)
                    active = Path(read_json(imported / "metadata/active-disk.json")["path"])
                    self.assertTrue(active.is_relative_to(imported))
                    self.check_chain(imported, active)
                    chain = call("snapshot", "chain", name)
                    self.assertIn(str(active), chain)
                    self.assertNotIn(str(bundle), chain)
                    self.assertIn("base-create", call("snapshot", "list", name))
                    call("snapshot", "restore", name, "base-create")
                    backing = Path(read_json(imported / "metadata/active-disk.json")["path"])
                    self.assertEqual(backing, imported / "disks/snapshots/base.qcow2")
                    io(self.qemu_io, backing, "read", 51, 8192)
                    call("snapshot", "disk-create", name, "base-create")
                api = request(sock, type="snapshot_chain", vm=name)
                self.assertEqual(api["type"], "snapshot_chain")
                self.assertEqual(len(api["chain"]["disks"]), 3)
                self.assertTrue(Path(api["chain"]["active_disk"]["path"])
                                .is_relative_to(imports[1]))
                untouched = digests(imports[1])
                selected = imports[0] / "disks/snapshots/base-create.qcow2"
                io(self.qemu_io, selected, "write", 85, 16384)
                io(self.qemu_io, selected, "read", 85, 16384)
                io(self.qemu_io, imports[1] / "disks/snapshots/base-create.qcow2", "read", 0, 16384)
                local("snapshot", "restore", name, "legacy snapshot")
                restored_root = Path(read_json(imports[0] / "metadata/active-disk.json")["path"])
                self.assertEqual(restored_root, imports[0] / "disks/root.qcow2")
                io(self.qemu_io, restored_root, "write", 102, 20480)
                io(self.qemu_io, restored_root, "read", 102, 20480)
                io(self.qemu_io, imports[1] / "disks/root.qcow2", "read", 0, 20480)
                self.assertEqual(digests(imports[1]), untouched)
                self.assertEqual(payload_digest(hidden_export), input_digest)
                self.assertEqual(digests(preserved_source), original)

    def test_directory_original_identity(self):
        self.scenario("directory", False)

    def test_directory_renamed_identity(self):
        self.scenario("directory", True)

    def test_tar_original_identity(self):
        self.scenario("tar", False)

    def test_tar_renamed_identity(self):
        self.scenario("tar", True)


    def test_encrypted_and_external_data_media_refuse_without_publication(self):
        for feature in ("encrypted", "external-data"):
            with self.subTest(feature=feature), tempfile.TemporaryDirectory(
                    prefix="bridgevm-unsafe-portable-", dir="/tmp") as temporary:
                root = Path(temporary).resolve()
                source = root / "source"
                call = endpoint(self.cli, store=source)
                call("create", NAME, "--os", "ubuntu", "--arch", "x86_64",
                     "--mode", "compatibility", "--disk", "8M", "--disk-format", "qcow2")
                bundle = source / f"vms/{NAME}.vmbridge"
                primary = bundle / "disks/root.qcow2"
                external = root / "external-data.raw"
                options = ("encrypt.format=luks,encrypt.key-secret=fixture-key" if feature == "encrypted"
                           else f"data_file={external},data_file_raw=on")
                secret = ("--object", "secret,id=fixture-key,data=synthetic-fixture-password") if feature == "encrypted" else ()
                run(self.qemu_img, "create", "-f", "qcow2", "-o", options, *secret, primary, "8M")
                info = json.loads(run(self.qemu_img, "info", "--output=json", primary))
                self.assertEqual(info["virtual-size"], 8 * 1024 * 1024)
                if feature == "encrypted":
                    self.assertTrue(info["encrypted"])
                else:
                    self.assertEqual(Path(info["format-specific"]["data"]["data-file"]), external)
                original = digests(bundle)
                outside_digest = payload_digest(external) if external.exists() else None
                exported = root / "unsupported.vmbridge"
                call("export", NAME, "--output", exported)
                input_digest = payload_digest(exported)
                local_target, remote_target = root / "local", root / "remote"
                with daemon(self.daemon_binary, remote_target) as sock:
                    for transport in (("--store", local_target), ("--socket", sock)):
                        message = refuse(self.cli, *transport, "import", exported)
                        if transport[0] == "--store":
                            self.assertIn("failed to import VM bundle", message)
                        self.assertIn(feature, message)
                        self.assertIn("unsupported", message)
                        self.assertEqual(payload_digest(exported), input_digest)
                    for target in (local_target, remote_target):
                        self.assertFalse((target / f"vms/{NAME}.vmbridge").exists())
                        self.assertEqual(list((target / "vms").iterdir()), [])
                self.assertEqual(digests(bundle), original)
                if outside_digest is not None:
                    self.assertEqual(payload_digest(external), outside_digest)


if __name__ == "__main__":
    unittest.main(verbosity=2)
