#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

SMOKES=(
  "tests/integration/template-create-cli-smoke.sh"
  "tests/integration/store-doctor-cli-smoke.sh"
  "tests/integration/mode-recommendation-cli-smoke.sh"
  "tests/integration/windows-arm-qemu-args-cli-smoke.sh"
  "tests/integration/clone-cli-smoke.sh"
  "tests/integration/metadata-repair-cli-smoke.sh"
  "tests/integration/manifest-migration-cli-smoke.sh"
  "tests/integration/manifest-schema-cli-smoke.sh"
  "tests/integration/export-import-cli-smoke.sh"
  "tests/integration/delete-cli-smoke.sh"
  "tests/integration/snapshot-metadata-create-list-cli-smoke.sh"
  "tests/integration/snapshot-disk-create-cli-smoke.sh"
  "tests/integration/snapshot-list-restore-cli-smoke.sh"
  "tests/integration/suspend-snapshot-cli-smoke.sh"
  "tests/integration/snapshot-active-disk-maintenance-cli-smoke.sh"
  "tests/integration/displayd-plan-cli-smoke.sh"
  "tests/integration/networkd-plan-cli-smoke.sh"
  "tests/integration/guest-tools-handshake-cli-smoke.sh"
  "tests/integration/guest-tools-time-sync-cli-smoke.sh"
  "tests/integration/guest-tools-clipboard-cli-smoke.sh"
  "tests/integration/guest-tools-display-resize-cli-smoke.sh"
  "tests/integration/guest-tools-shared-folder-cli-smoke.sh"
  "tests/integration/guest-tools-file-drop-cli-smoke.sh"
  "tests/integration/guest-tools-app-window-cli-smoke.sh"
  "tests/integration/guest-tools-command-tracker-cli-smoke.sh"
  "tests/integration/guest-tools-agent-update-cli-smoke.sh"
  "tests/integration/guest-tools-metrics-cli-smoke.sh"
  "tests/integration/disk-create-inspect-cli-smoke.sh"
  "tests/integration/disk-verify-cli-smoke.sh"
  "tests/integration/disk-compact-cli-smoke.sh"
  "tests/integration/fast-mode-template-boot-media-smoke.sh"
  "tests/integration/boot-media-download-fake-curl-smoke.sh"
  "tests/integration/fast-mode-readiness-smoke.sh"
  "tests/integration/fast-mode-readiness-unsupported-smoke.sh"
  "tests/integration/fast-mode-readiness-template-matrix-smoke.sh"
  "tests/integration/readiness-report-cli-smoke.sh"
  "tests/integration/shared-folder-manifest-cli-smoke.sh"
  "tests/integration/port-forward-cli-smoke.sh"
  "tests/integration/qemu-host-only-cli-smoke.sh"
  "tests/integration/qmp-control-cli-smoke.sh"
  "tests/integration/qmp-supervisor-cli-smoke.sh"
  "tests/integration/ssh-plan-cli-smoke.sh"
  "tests/integration/lifecycle-plan-cli-smoke.sh"
  "tests/integration/lifecycle-restart-cli-smoke.sh"
  "tests/integration/lifecycle-suspend-resume-cli-smoke.sh"
  "tests/integration/application-consistent-snapshot-cli-smoke.sh"
  "tests/integration/application-consistent-freeze-thaw-cli-smoke.sh"
  "tests/integration/application-consistent-fsfreeze-backend-smoke.sh"
  "tests/integration/log-viewer-cli-smoke.sh"
  "tests/integration/diagnostics-cli-smoke.sh"
  "tests/integration/performance-cli-smoke.sh"
  "tests/integration/resource-profile-readiness-smoke.sh"
  "tests/integration/runtime-resource-policy-cli-smoke.sh"
  "tests/sleep-wake/metadata-baseline-smoke.sh"
  "tests/integration/apple-vz-live-evidence-verifier-smoke.sh"
  "tests/integration/qemu-live-evidence-verifier-smoke.sh"
  "tests/integration/qemu-live-fixture-prep-smoke.sh"
  "tests/integration/macos-settings-defaults-smoke.sh"
  "tests/integration/macos-app-start-path-smoke.sh"
  "tests/integration/apple-vz-live-opt-in-skip-smoke.sh"
  "tests/integration/qemu-live-opt-in-skip-smoke.sh"
)

cd "$ROOT"

for smoke in "${SMOKES[@]}"; do
  echo "==> $smoke"
  "$ROOT/$smoke"
done

echo "PASS: metadata-safe smoke suite"
