#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

assert_contains() {
  local haystack="$1"
  local needle="$2"
  local label="$3"
  case "$haystack" in
    *"$needle"*) ;;
    *) fail "$label missing '$needle'; got: $haystack" ;;
  esac
}

assert_not_matches() {
  local haystack="$1"
  local pattern="$2"
  local label="$3"
  if grep -Eq "$pattern" <<<"$haystack"; then
    fail "$label unexpectedly matched /$pattern/: $haystack"
  fi
}

output="$(
  env \
    -u BRIDGEVM_LIVE_GUEST_TOOLS_ALLOW_REAL_START \
    -u BRIDGEVM_LIVE_GUEST_TOOLS_QCOW2_DISK \
    tests/integration/product-gates-report.sh
)"

assert_contains "$output" "BridgeVM product gates report" "product gates report"
assert_contains "$output" "No percentage estimate" "product gates report"
assert_contains "$output" "Current wall: convert preserved live proofs into a secure, turnkey, distributable product." "product gates report"
assert_contains "$output" "Next engineering gates: finish Secure Boot/measured-boot receipts and finalize a signed ARM64 viogpu3d render package" "product gates report"
assert_contains "$output" "Product decision: durable disk-backed suspend is explicitly outside Windows HVF v1" "product gates report"
assert_contains "$output" "Release gate: package and notarize the app" "product gates report"
assert_contains "$output" "Fast/VZ GUI display" "product gates report"
assert_contains "$output" "Apple VZ Linux template/staging" "product gates report"
assert_contains "$output" "debian-arm64-apple-vz-linux-kernel-raw and ubuntu-arm64-apple-vz-linux-kernel-raw create Fast Mode linux-kernel/raw-disk VMs" "product gates report"
assert_contains "$output" "prepare-run writes metadata/apple-vz-launch.json with Launch ready: true" "product gates report"
assert_contains "$output" "Ubuntu carries a desktop-target graphical kernel command line" "product gates report"
assert_contains "$output" "no backend or GUI process is spawned" "product gates report"
assert_contains "$output" "Ubuntu cloudimg Apple VZ preparation" "product gates report"
assert_contains "$output" "prepare-vz-ubuntu-cloudimg-fixture.sh produces vmlinuz, initrd, root.raw, and artifacts.json" "product gates report"
assert_contains "$output" "whole-disk ext4 root=/dev/vda Apple VZ linux-kernel/raw handoff" "product gates report"
assert_contains "$output" "without QEMU runtime, AppleVzRunner live start, or GUI spawn" "product gates report"
assert_contains "$output" "Ubuntu qcow2-to-Apple-VZ artifact preparation" "product gates report"
assert_contains "$output" "prepare-vz-ubuntu-arm64-boot-artifacts.sh records qemu-img as offline inspection/conversion only" "product gates report"
assert_contains "$output" "derives a root=UUID kernel command line instead of assuming /dev/vda2" "product gates report"
assert_contains "$output" "without qemu-system, AppleVzRunner live start, or GUI spawn" "product gates report"
assert_contains "$output" "Coherence-lite" "product gates report"
assert_contains "$output" "Ubuntu GUI live opt-in" "product gates report"
assert_contains "$output" "Windows no-QEMU fast path" "product gates report"
assert_contains "$output" "RESEARCH Windows no-QEMU fast path" "product gates report"
assert_contains "$output" "installed Windows 11 ARM64 desktop, four vCPUs, virtio-net connectivity" "product gates report"
assert_contains "$output" "PASS     Windows HVF xHCI HID boot-key report boundary -" "product gates report"
assert_contains "$output" "queued USB boot-keyboard Space [00 00 2c 00 00 00 00 00] plus release [00 00 00 00 00 00 00 00] over BridgeVM-owned xHCI DCI3" "product gates report"
assert_contains "$output" "This isolated metadata boundary does not itself claim Windows boot" "product gates report"
assert_contains "$output" "separate installed-target live evidence covers the later desktop path" "product gates report"
assert_contains "$output" "Windows HVF VMM" "product gates report"
assert_contains "$output" "PARTIAL  Windows HVF VMM" "product gates report"
assert_contains "$output" "four logical processors, virtio-net DHCP/DNS/HTTP/ICMP connectivity" "product gates report"
assert_contains "$output" "9/9 valid round-robin performance matrix" "product gates report"
assert_contains "$output" "current engineering gates are secure turnkey packaging/UX, PPI/Secure Boot lifecycle receipts" "product gates report"
assert_contains "$output" "QEMU's exact 6-byte etc/tpm/config record that activates the pinned EDK2 PPI request processor only with a concrete backend" "product gates report"
assert_contains "$output" "completed 1,032 TPM commands" "product gates report"
assert_contains "$output" "PPI reads occurred but writes did not" "product gates report"
assert_contains "$output" "a live Windows PPI-action receipt" "product gates report"
assert_contains "$output" "PARTIAL  Windows ARM64 viogpu3d artifact" "product gates report"
assert_contains "$output" "test-signed ARM64 INF/SYS/CAT packages for Venus and VirGL" "product gates report"
assert_contains "$output" "VirGL full package with five ARM64 Mesa DLLs" "product gates report"
assert_contains "$output" "three are KMD-only" "product gates report"
assert_contains "$output" "omits UserModeDriverName, OpenGLDriverName, OpenGLVersion, OpenGLFlags, and InstalledDisplayDrivers INF registrations" "product gates report"
assert_contains "$output" "BLOCKED  Windows ARM64 viogpu3d render package" "product gates report"
assert_contains "$output" "No preserved package currently satisfies the repository's render-candidate gate" "product gates report"
assert_contains "$output" "Run the Windows WDK finalizer with the pre-finalization manifest" "product gates report"
assert_contains "$output" "parser-only dummy catalog is not signature evidence" "product gates report"
assert_contains "$output" "BLOCKED  Windows ARM64 viogpu3d live bind/trace" "product gates report"
assert_contains "$output" "After a finalized UMD-registered package passes the render-candidate gate" "product gates report"
assert_contains "$output" "Status OK bound to the intended OEM INF" "product gates report"
assert_contains "$output" "Windows HVF GICv3 skeleton" "product gates report"
assert_contains "$output" "GICv3 distributor/redistributor MMIO register skeleton is wired to the Windows firmware bus" "product gates report"
assert_contains "$output" "single-vCPU Group1 ICC_* CPU-interface sysreg skeleton" "product gates report"
assert_contains "$output" "status and group modifier registers" "product gates report"
assert_contains "$output" "ICC_RPR_EL1" "product gates report"
assert_contains "$output" "ICC_AP0R*/ICC_AP1R*" "product gates report"
assert_contains "$output" "GICD EnableGrp1NS plus GICD/GICR IGROUPR Group1 bits" "product gates report"
assert_contains "$output" "Full GIC delivery beyond the minimal single-vCPU SPI/PPI paths" "product gates report"
assert_contains "$output" "highest-priority pending enabled Group1 interrupt across redistributor PPI and distributor SPI candidates" "product gates report"
assert_contains "$output" "PMR/current-running-priority threshold" "product gates report"
assert_contains "$output" "handled MMIO read/write counts" "product gates report"
assert_contains "$output" "per-device MMIO counts" "product gates report"
assert_contains "$output" "virtio queue_notify/request completion counts" "product gates report"
assert_contains "$output" "handled ICC read/write counts" "product gates report"
assert_contains "$output" "per-ICC_IAR1/ICC_EOIR1/ICC_DIR counts" "product gates report"
assert_contains "$output" "last ICC_IAR1/ICC_EOIR1/ICC_DIR INTIDs" "product gates report"
assert_contains "$output" "ICC_CTLR_EL1 EOImode" "product gates report"
assert_contains "$output" "require ICC_DIR_EL1 for deactivate when EOImode is set" "product gates report"
assert_contains "$output" "complete GIC emulation are not complete" "product gates report"
assert_contains "$output" "Windows HVF machine-plan metadata" "product gates report"
assert_contains "$output" "bridgevm hvf machine-plan and hvf-runner --machine-plan" "product gates report"
assert_contains "$output" "HVF VM create/destroy probe boundary" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_VM_CREATE=1" "product gates report"
assert_contains "$output" "com.apple.security.hypervisor" "product gates report"
assert_contains "$output" "HVF vCPU create/destroy probe boundary" "product gates report"
assert_contains "$output" "does not call hv_vcpu_run" "product gates report"
assert_contains "$output" "HVF vCPU run/cancel probe boundary" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_VCPU_RUN=1" "product gates report"
assert_contains "$output" "pre-cancels hv_vcpu_run" "product gates report"
assert_contains "$output" "HVF interrupt/timer probe boundary" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_INTERRUPT_TIMER=1" "product gates report"
assert_contains "$output" "hv_vcpu_set/get_pending_interrupt" "product gates report"
assert_contains "$output" "hv_vcpu_set/get_vtimer_mask" "product gates report"
assert_contains "$output" "hv_vcpu_set/get_vtimer_offset" "product gates report"
assert_contains "$output" "HVF VTimer exit probe boundary" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_VTIMER_EXIT=1" "product gates report"
assert_contains "$output" "CNTV_CVAL_EL0" "product gates report"
assert_contains "$output" "CNTV_CTL_EL0" "product gates report"
assert_contains "$output" "HV_EXIT_REASON_VTIMER_ACTIVATED" "product gates report"
assert_contains "$output" "automatic VTimer mask" "product gates report"
assert_contains "$output" "timer-exit VMM boundary" "product gates report"
assert_contains "$output" "HVF memory map/unmap probe boundary" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_MEMORY_MAP=1" "product gates report"
assert_contains "$output" "one 16 KiB guest RAM page" "product gates report"
assert_contains "$output" "HVF guest entry probe boundary" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_GUEST_ENTRY=1" "product gates report"
assert_contains "$output" "one HVC instruction" "product gates report"
assert_contains "$output" "HVF guest exit loop probe boundary" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_EXIT_LOOP=1" "product gates report"
assert_contains "$output" "two HVC exits" "product gates report"
assert_contains "$output" "HVF MMIO read exit probe boundary" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_MMIO_READ=1" "product gates report"
assert_contains "$output" "IPA 0x50000000" "product gates report"
assert_contains "$output" "HVF MMIO read emulation probe boundary" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_MMIO_EMULATION=1" "product gates report"
assert_contains "$output" "0x123456789abcdef0" "product gates report"
assert_contains "$output" "HVF MMIO write emulation probe boundary" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_MMIO_WRITE_EMULATION=1" "product gates report"
assert_contains "$output" "0xfedcba987654321" "product gates report"
assert_contains "$output" "HVF MMIO serial device probe boundary" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_MMIO_SERIAL_DEVICE=1" "product gates report"
assert_contains "$output" "BridgeVM MMIO device bus" "product gates report"
assert_contains "$output" "PL011 UART" "product gates report"
assert_contains "$output" "0x41" "product gates report"
assert_contains "$output" "0x90" "product gates report"
assert_contains "$output" "HVF MMIO RTC device probe boundary" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_MMIO_RTC_DEVICE=1" "product gates report"
assert_contains "$output" "PL031 RTC" "product gates report"
assert_contains "$output" "0x20260618" "product gates report"
assert_contains "$output" "HVF MMIO block device probe boundary" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_MMIO_BLOCK_DEVICE=1" "product gates report"
assert_contains "$output" "VirtIO-MMIO" "product gates report"
assert_contains "$output" "0x74726976" "product gates report"
assert_contains "$output" "0x4252564d" "product gates report"
assert_contains "$output" "HVF MMIO block queue/config/address/notify probe boundary" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_MMIO_BLOCK_QUEUE=1" "product gates report"
assert_contains "$output" "queue select/size/ready" "product gates report"
assert_contains "$output" "descriptor/driver/device ring addresses" "product gates report"
assert_contains "$output" "queue notify" "product gates report"
assert_contains "$output" "interrupt status" "product gates report"
assert_contains "$output" "capacity registers" "product gates report"
assert_contains "$output" "PC instruction word/hint" "product gates report"
assert_contains "$output" "EL1 exception/vector sysregs" "product gates report"
assert_contains "$output" "EL1 MMU translation sysreg snapshots" "product gates report"
assert_contains "$output" "EL1-executable leaf candidate scan" "product gates report"
assert_contains "$output" "vector-sync VA/PA/instruction/hint telemetry" "product gates report"
assert_contains "$output" "2 KiB-aligned vector-base scan/suppression/limit telemetry plus passive recommended-vector-base selection and opt-in one-shot recommended-vector-base VBAR set and follow-up-exit telemetry" "product gates report"
assert_contains "$output" "automatic diagnosis classification" "product gates report"
assert_contains "$output" "Windows HVF low-vector resume telemetry" "product gates report"
assert_contains "$output" "repair-and-resume-once telemetry" "product gates report"
assert_contains "$output" "Preserved opt-in live smoke output records" "product gates report"
assert_contains "$output" "continue-after-low-vector-repair option" "product gates report"
assert_contains "$output" "metadata-safe no-opt-in smoke that records Continue after low-vector repair requested: true" "product gates report"
assert_contains "$output" "Continue after low-vector repair attempted: false" "product gates report"
assert_contains "$output" "post-repair unsupported exit reason/classification plus first-device-interaction and first-unhandled-access telemetry remain not observed without live opt-in" "product gates report"
assert_contains "$output" "--restore-low-vector-slot-before-eret opt-in" "product gates report"
assert_contains "$output" "executable ERET trampoline" "product gates report"
assert_contains "$output" "instruction_word_after_exit == AARCH64_ERET" "product gates report"
assert_contains "$output" "erased-pflash-execution rather than another synthetic diagnostic-page stop" "product gates report"
assert_contains "$output" "not UEFI Boot Manager handoff, installer boot, Windows boot, GUI, network, TPM, Secure Boot, or a usable Windows fast path" "product gates report"
assert_contains "$output" "entry IPA 0xc000" "product gates report"
assert_contains "$output" "previous descriptor 0x0" "product gates report"
assert_contains "$output" "descriptor=0xf8f" "product gates report"
assert_contains "$output" "HV_EXIT_REASON_VTIMER_ACTIVATED" "product gates report"
assert_contains "$output" "UEFI Boot Manager handoff" "product gates report"
assert_contains "$output" "Windows HVF boot-disk layout boundary" "product gates report"
assert_contains "$output" "bridgevm hvf windows-boot-disk-layout-probe" "product gates report"
assert_contains "$output" "hvf-runner --windows-boot-disk-layout-probe" "product gates report"
assert_contains "$output" "protective MBR, primary/backup GPT, ESP, MSR, and Windows Basic Data" "product gates report"
assert_contains "$output" "Windows HVF firmware handoff boundary" "product gates report"
assert_contains "$output" "bridgevm hvf windows-firmware-handoff-probe" "product gates report"
assert_contains "$output" "hvf-runner --windows-firmware-handoff-probe" "product gates report"
assert_contains "$output" "verify FV checksums" "product gates report"
assert_contains "$output" "planned code/vars pflash IPA slots" "product gates report"
assert_contains "$output" "Windows HVF pflash map boundary" "product gates report"
assert_contains "$output" "bridgevm hvf windows-pflash-map-probe" "product gates report"
assert_contains "$output" "hvf-runner --windows-pflash-map-probe" "product gates report"
assert_contains "$output" "load code/vars into planned 64 MiB pflash memory images" "product gates report"
assert_contains "$output" "non-overlapping IPA ranges" "product gates report"
assert_contains "$output" "device MMIO separation" "product gates report"
assert_contains "$output" "Windows HVF pflash HVF map boundary" "product gates report"
assert_contains "$output" "bridgevm hvf windows-pflash-hvf-map-probe" "product gates report"
assert_contains "$output" "hvf-runner --windows-pflash-hvf-map-probe" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_UEFI_PFLASH_MAP=1" "product gates report"
assert_contains "$output" "code read|exec and vars read|write IPA slots" "product gates report"
assert_contains "$output" "without QEMU, Apple VZ, GUI launch, vCPU creation, or guest execution" "product gates report"
assert_contains "$output" "Windows HVF reset-vector entry boundary" "product gates report"
assert_contains "$output" "bridgevm hvf windows-reset-vector-entry-probe" "product gates report"
assert_contains "$output" "hvf-runner --windows-reset-vector-entry-probe" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_UEFI_RESET_VECTOR_ENTRY=1" "product gates report"
assert_contains "$output" "set PC/CPSR" "product gates report"
assert_contains "$output" "enter the UEFI reset vector once under a watchdog" "product gates report"
assert_contains "$output" "classify the Arm exception class" "product gates report"
assert_contains "$output" "PC progressed beyond the reset vector" "product gates report"
assert_contains "$output" "Windows boot claims" "product gates report"
assert_contains "$output" "Windows HVF firmware run-loop boundary" "product gates report"
assert_contains "$output" "bridgevm hvf windows-firmware-run-loop-probe" "product gates report"
assert_contains "$output" "hvf-runner --windows-firmware-run-loop-probe" "product gates report"
assert_contains "$output" "Windows HVF firmware device-discovery boundary" "product gates report"
assert_contains "$output" "bridgevm hvf windows-firmware-device-discovery-probe" "product gates report"
assert_contains "$output" "hvf-runner --windows-firmware-device-discovery-probe" "product gates report"
assert_contains "$output" "named no-QEMU device-discovery gate" "product gates report"
assert_contains "$output" "stop-at-first-post-repair-device-boundary policy" "product gates report"
assert_contains "$output" "Device discovery boundary reached/status/ready plus blockers" "product gates report"
assert_contains "$output" "Windows HVF GICv3 skeleton" "product gates report"
assert_contains "$output" "single-vCPU Group1 ICC_* CPU-interface sysreg skeleton" "product gates report"
assert_contains "$output" "ICC_IAR1_EL1" "product gates report"
assert_contains "$output" "ICC_EOIR1_EL1" "product gates report"
assert_contains "$output" "ICC_DIR_EL1" "product gates report"
assert_contains "$output" "conservative Group0/AP/RPR/SGI stubs" "product gates report"
assert_contains "$output" "gates assertion on GICD EnableGrp1NS, GICD/GICR IGROUPR Group1 bits" "product gates report"
assert_contains "$output" "lets ICC_HPPIR1/ICC_IAR1 choose the highest-priority pending Group1 PPI/SPI" "product gates report"
assert_contains "$output" "moves the acknowledged INTID active" "product gates report"
assert_contains "$output" "treats ICC_EOIR1 as priority drop plus deactivate when ICC_CTLR EOImode is clear" "product gates report"
assert_contains "$output" "requires ICC_DIR for deactivate when EOImode is set" "product gates report"
assert_contains "$output" "refreshes/re-pends level VirtIO sources after actual deactivation" "product gates report"
assert_contains "$output" "virtual timer PPI 11 / INTID 27" "product gates report"
assert_contains "$output" "routes the virtual timer PPI 11 / INTID 27 through the same single-vCPU GIC CPU-interface path" "product gates report"
assert_contains "$output" "Full GIC delivery beyond the minimal single-vCPU SPI/PPI paths" "product gates report"
assert_contains "$output" "complete nested preemption, binary-point/List Register behavior" "product gates report"
assert_contains "$output" "complete deactivation-stack semantics" "product gates report"
assert_contains "$output" "multi-vCPU routing" "product gates report"
assert_contains "$output" "BRIDGEVM_HVF_ALLOW_UEFI_FIRMWARE_RUN_LOOP=1" "product gates report"
assert_contains "$output" "map code read|exec pflash, vars read|write pflash, guest RAM read|write|exec, and optional low pflash aliases" "product gates report"
assert_contains "$output" "populate the FDT platform DTB in guest RAM at 0x40010000" "product gates report"
assert_contains "$output" "set PC/X0-DTB/CPSR/SP_EL1" "product gates report"
assert_contains "$output" "optionally seed a pflash, guest-RAM, or executable-candidate diagnostic VBAR/vector slot" "product gates report"
assert_contains "$output" "classify bounded firmware exits" "product gates report"
assert_contains "$output" "watchdog timeout, ESR abort details, mapped-region hints, PC instruction word/hint, X0-X4/CPSR, EL1 exception/vector sysregs, EL1 MMU translation sysreg snapshots, PC stage-1 leaf descriptor/XN bits plus descriptor samples and walk entries for low-vector, pflash, guest-RAM, executable-vector, PC, VBAR, ELR, FAR, and SP addresses plus an EL1-executable leaf candidate scan with vector-sync VA/PA/instruction/hint telemetry plus 2 KiB-aligned vector-base scan/suppression/limit telemetry plus passive recommended-vector-base selection and opt-in one-shot recommended-vector-base VBAR set and follow-up-exit telemetry, automatic diagnosis classification, first firmware data-abort MMIO routing" "product gates report"
assert_contains "$output" "expose installer ISO plus writable target disk metadata" "product gates report"
assert_contains "$output" "installer ISO at 0x10002000 read-only" "product gates report"
assert_contains "$output" "target disk at 0x10003000 writable" "product gates report"
assert_contains "$output" "device IRQ line boundary" "product gates report"
assert_contains "$output" "VirtIO used-buffer interrupt status into GICD FDT SPI pending bits" "product gates report"
assert_contains "$output" "asserts/deasserts the HVF IRQ line on edge changes" "product gates report"
assert_contains "$output" "device IRQ line assert/deassert counts and status names" "product gates report"
assert_contains "$output" "handled MMIO read/write counts, per-device MMIO counts, virtio queue_notify/request completion counts" "product gates report"
assert_contains "$output" "VirtIO-status-to-GICD-SPI-to-priority-selected-ICC-IAR/EOIR/DIR-to-HVF-line skeleton boundary plus minimal timer PPI-to-GIC CPU-interface delivery" "product gates report"
assert_contains "$output" "not full GIC emulation" "product gates report"
assert_contains "$output" "complete nested interrupt preemption, binary-point/List Register behavior" "product gates report"
assert_contains "$output" "without QEMU, Apple VZ, GUI launch, UEFI Boot Manager, or Windows boot claims" "product gates report"
assert_contains "$output" "Windows HVF platform-description boundary" "product gates report"
assert_contains "$output" "bridgevm hvf windows-platform-description-probe" "product gates report"
assert_contains "$output" "hvf-runner --windows-platform-description-probe" "product gates report"
assert_contains "$output" "metadata-only FDT platform description" "product gates report"
assert_contains "$output" "FDT magic 0xd00dfeed" "product gates report"
assert_contains "$output" "guest RAM at 0x40000000" "product gates report"
assert_contains "$output" "PL011/PL031 plus VirtIO-MMIO installer ISO at 0x10002000 and target disk at 0x10003000 inside the 0x10000000..0x20000000 Windows device window" "product gates report"
assert_contains "$output" "root interrupt-parent 0x1" "product gates report"
assert_contains "$output" "GICv3 distributor/redistributor ranges" "product gates report"
assert_contains "$output" "four ARM arch timer interrupts" "product gates report"
assert_contains "$output" "PL011/PL031/VirtIO FDT SPI interrupt cells 0..3" "product gates report"
assert_contains "$output" "ACPI not implemented, fw_cfg not used, GIC described/not emulated, GIC emulated false" "product gates report"
assert_contains "$output" "no QEMU, Apple VZ, GUI launch, HVF entry, UEFI Boot Manager, installer boot, or Windows boot claims" "product gates report"
assert_contains "$output" "seeds one synthetic VirtIO block read request in guest RAM" "product gates report"
assert_contains "$output" "completes it immediately after queue_notify" "product gates report"
assert_contains "$output" "optional --disk/--iso/--writable-disk backing selectors" "product gates report"
assert_contains "$output" "host-file backing" "product gates report"
assert_contains "$output" "used-buffer interrupt status" "product gates report"
assert_contains "$output" "VirtIO block request model boundary" "product gates report"
assert_contains "$output" "configured through MMIO bus writes" "product gates report"
assert_contains "$output" "observe queue notify" "product gates report"
assert_contains "$output" "through the device bus" "product gates report"
assert_contains "$output" "VIRTIO_BLK_T_IN" "product gates report"
assert_contains "$output" "used ring" "product gates report"
assert_contains "$output" "do not prove live HVF block IO" "product gates report"
assert_contains "$output" "VirtIO block host-file backing boundary" "product gates report"
assert_contains "$output" "host disk image fixture" "product gates report"
assert_contains "$output" "byte offset 0xe00" "product gates report"
assert_contains "$output" "metadata-safe host-backed storage read model" "product gates report"
assert_contains "$output" "signed opt-in mmio-block-queue --disk path" "product gates report"
assert_contains "$output" "VirtIO block writable host-file backing boundary" "product gates report"
assert_contains "$output" "VIRTIO_BLK_T_FLUSH" "product gates report"
assert_contains "$output" "read/write/flush/reopen persistence boundary" "product gates report"
assert_contains "$output" "signed opt-in mmio-block-queue --writable-disk path" "product gates report"
assert_contains "$output" "partition install state" "product gates report"
assert_contains "$output" "VirtIO block ISO backing boundary" "product gates report"
assert_contains "$output" "read-only installer-media fixture" "product gates report"
assert_contains "$output" "VIRTIO_BLK_T_OUT" "product gates report"
assert_contains "$output" "S_IOERR" "product gates report"
assert_contains "$output" "metadata-safe read-only installer media sector-read and write-rejection model" "product gates report"
assert_contains "$output" "not UEFI boot" "product gates report"
assert_contains "$output" "Parallels-style true Coherence" "product gates report"
assert_contains "$output" "BLOCKED  Public release readiness boundary" "product gates report"
assert_not_matches "$output" 'Parallels replacement' "product gates report"
assert_contains "$output" "BRIDGEVM_LIVE_GUEST_TOOLS_ALLOW_REAL_START=1 not set" "product gates report"
assert_not_matches "$output" '[0-9]+%' "product gates report"

echo "PASS: product gates report smoke"
