#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

STORE="$(mktemp -d "/tmp/bridgevm-winarm-hvf-platform-description-runner.XXXXXX")"
FAKE_BIN="$STORE/bin"
BACKEND_LOG="$STORE/backend-launch.log"

# shellcheck source=/dev/null
source "$ROOT/tests/integration/windows-arm-hvf-pflash-fixtures.sh"

install_backend_guards "Windows Arm HVF platform-description runner smoke"

output="$(cargo run -q -p hvf-runner -- --windows-platform-description-probe --memory-gib 8 --vcpus 6 2>&1)" \
  || fail "hvf-runner --windows-platform-description-probe command failed: $output"

assert_contains "$output" "Windows 11 Arm HVF platform description probe" "Windows Arm platform-description runner output"
assert_contains "$output" "QEMU: not used" "Windows Arm platform-description runner output"
assert_contains "$output" "Apple VZ: not used" "Windows Arm platform-description runner output"
assert_contains "$output" "HVF: not entered" "Windows Arm platform-description runner output"
assert_contains "$output" "Guest execution: not entered; metadata-only FDT platform description" "Windows Arm platform-description runner output"
assert_contains "$output" "Format: FDT" "Windows Arm platform-description runner output"
assert_contains "$output" "FDT magic: 0xd00dfeed" "Windows Arm platform-description runner output"
assert_contains "$output" "FDT magic verified: true" "Windows Arm platform-description runner output"
assert_contains "$output" "Memory node base: 0x40000000" "Windows Arm platform-description runner output"
assert_contains "$output" "Memory node at 0x40000000: true" "Windows Arm platform-description runner output"
assert_contains "$output" "Requested CPU count: 6" "Windows Arm platform-description runner output"
assert_contains "$output" "CPU count: 6" "Windows Arm platform-description runner output"
assert_contains "$output" "CPU count verified: true" "Windows Arm platform-description runner output"
assert_contains "$output" "Device MMIO window: 0x10000000..0x20000000" "Windows Arm platform-description runner output"
assert_contains "$output" "PL011/PL031/VirtIO-MMIO installer ISO/target disk nodes inside device window: true" "Windows Arm platform-description runner output"
assert_contains "$output" "PL011 node: serial@10000000" "Windows Arm platform-description runner output"
assert_contains "$output" "PL031 node: rtc@10001000" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO installer ISO node: virtio_mmio@10002000" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO installer ISO node base: 0x10002000" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO installer ISO node bytes: 0x1000" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO target disk node: virtio_mmio@10003000" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO target disk node base: 0x10003000" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO target disk node bytes: 0x1000" "Windows Arm platform-description runner output"
assert_contains "$output" "PL011 node inside device window: true" "Windows Arm platform-description runner output"
assert_contains "$output" "PL031 node inside device window: true" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO installer ISO node inside device window: true" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO target disk node inside device window: true" "Windows Arm platform-description runner output"
assert_contains "$output" "Root interrupt-parent: 0x1" "Windows Arm platform-description runner output"
assert_contains "$output" "GIC phandle: 0x1" "Windows Arm platform-description runner output"
assert_contains "$output" "GIC distributor base: 0x10010000" "Windows Arm platform-description runner output"
assert_contains "$output" "GIC distributor bytes: 0x10000" "Windows Arm platform-description runner output"
assert_contains "$output" "GIC redistributor base: 0x10020000" "Windows Arm platform-description runner output"
assert_contains "$output" "GIC redistributor bytes: 0xc0000" "Windows Arm platform-description runner output"
assert_contains "$output" "GIC nodes inside device window: true" "Windows Arm platform-description runner output"
assert_contains "$output" "ARM arch timer node present: true" "Windows Arm platform-description runner output"
assert_contains "$output" "ARM arch timer interrupt count: 4" "Windows Arm platform-description runner output"
assert_contains "$output" "Interrupt nodes described: true" "Windows Arm platform-description runner output"
assert_contains "$output" "PL011 interrupt node: serial@10000000" "Windows Arm platform-description runner output"
assert_contains "$output" "PL011 interrupt type: 0x0" "Windows Arm platform-description runner output"
assert_contains "$output" "PL011 interrupt number: 0x0" "Windows Arm platform-description runner output"
assert_contains "$output" "PL011 interrupt trigger: 0x4" "Windows Arm platform-description runner output"
assert_contains "$output" "PL011 interrupt described: true" "Windows Arm platform-description runner output"
assert_contains "$output" "PL031 interrupt node: rtc@10001000" "Windows Arm platform-description runner output"
assert_contains "$output" "PL031 interrupt type: 0x0" "Windows Arm platform-description runner output"
assert_contains "$output" "PL031 interrupt number: 0x1" "Windows Arm platform-description runner output"
assert_contains "$output" "PL031 interrupt trigger: 0x4" "Windows Arm platform-description runner output"
assert_contains "$output" "PL031 interrupt described: true" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO installer ISO interrupt node: virtio_mmio@10002000" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO installer ISO interrupt type: 0x0" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO installer ISO interrupt number: 0x2" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO installer ISO interrupt trigger: 0x4" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO installer ISO interrupt described: true" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO target disk interrupt node: virtio_mmio@10003000" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO target disk interrupt type: 0x0" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO target disk interrupt number: 0x3" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO target disk interrupt trigger: 0x4" "Windows Arm platform-description runner output"
assert_contains "$output" "VirtIO-MMIO target disk interrupt described: true" "Windows Arm platform-description runner output"
assert_contains "$output" "ACPI: not implemented" "Windows Arm platform-description runner output"
assert_contains "$output" "fw_cfg: not used" "Windows Arm platform-description runner output"
assert_contains "$output" "GIC: described/not emulated" "Windows Arm platform-description runner output"
assert_contains "$output" "GIC emulated: false" "Windows Arm platform-description runner output"
assert_contains "$output" "Blockers: none" "Windows Arm platform-description runner output"
assert_not_contains "$output" "qemu-system" "Windows Arm platform-description runner output"
assert_not_matches "$output" '[0-9]+([.][0-9]+)?%' "Windows Arm platform-description runner output"
assert_no_backend_launch

echo "PASS: Windows 11 Arm no-QEMU HVF platform-description runner smoke ($STORE)"
