#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

STORE="$(mktemp -d "/tmp/bridgevm-winarm-hvf-firmware-run-loop-runner.XXXXXX")"
FAKE_BIN="$STORE/bin"
BACKEND_LOG="$STORE/backend-launch.log"
FIRMWARE="$STORE/AAVMF_CODE.fd"
VARS_TEMPLATE="$STORE/AAVMF_VARS.fd"
VARS="$STORE/win11-arm-vars.fd"
CONTINUE_VARS="$STORE/win11-arm-continue-vars.fd"
ISO="$STORE/Win11_Arm64.iso"
DISK="$STORE/windows-arm.raw"

# shellcheck source=/dev/null
source "$ROOT/tests/integration/windows-arm-hvf-pflash-fixtures.sh"

install_backend_guards "Windows Arm HVF firmware run-loop runner smoke"
write_uefi_fv_fixture "$FIRMWARE" 131072
write_uefi_fv_fixture "$VARS_TEMPLATE" 65536

output="$(cargo run -q -p hvf-runner -- --windows-firmware-run-loop-probe --firmware "$FIRMWARE" --vars-template "$VARS_TEMPLATE" --vars "$VARS" --create-vars --iso "$ISO" --writable-disk "$DISK" 2>&1)" \
  || fail "hvf-runner --windows-firmware-run-loop-probe command failed: $output"

assert_contains "$output" "Windows 11 Arm HVF UEFI firmware run-loop probe" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "QEMU: not used" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Apple VZ: not used" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Guest execution: bounded UEFI firmware exit classification loop" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Windows boot: not claimed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Allowed: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Attempted: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "VM created: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Guest RAM memory allocated: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low firmware alias mapped: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vars alias mapped: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Guest RAM memory mapped: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Platform DTB populated: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page previous descriptor: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page slot restored: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page restore before ERET requested: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page restore before ERET attempted: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page repeated fault observed: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector recommended-vector remap requested: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector recommended-vector remap attempted: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector recommended-vector remap succeeded: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector recommended-vector remap target PA: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector recommended-vector remap descriptor: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Continue after low-vector repair requested: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Continue after low-vector repair attempted: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair unsupported exit observed: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair unsupported exit reason name: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair unsupported exit classification: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first exit access kind: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first exit access direction: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first exit access address: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first exit access sysreg: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first exit access syndrome: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first device interaction observed: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first device interaction: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first device interaction reason name: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first device interaction classification: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first device interaction PC: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first device interaction access kind: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first device interaction access direction: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first device interaction access address: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first device interaction access sysreg: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first device interaction access syndrome: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first device interaction kind: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first unhandled access observed: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first unhandled access: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first unhandled access reason name: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first unhandled access classification: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first unhandled access kind: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first unhandled access direction: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first unhandled access handler result: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first unhandled access MMIO device kind: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Post-repair first unhandled access sysreg name: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page resume attempted: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page resume armed: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page resume original PC: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page resume original ELR_EL1: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page resume original ESR_EL1: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page resume original FAR_EL1: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page resume original SPSR_EL1: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR requested: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR attempted: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR set: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR diagnostic vector populated: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR resume requested: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR resume attempted: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR resume armed: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "vCPU created: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "PC set: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "X0 DTB IPA set: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "CPSR set: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Interrupt/timer wiring requested: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Interrupt/timer initialized: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Run loop attempted: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Firmware progress observed: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Unsupported exit observed: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Pflash map verified: true" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low firmware alias IPA: 0x0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vars alias IPA: 0x4000000" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Guest RAM IPA: 0x40000000" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Platform DTB IPA: 0x40010000" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Platform DTB guest RAM offset: 0x10000" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Diagnostic vector location: pflash" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR source exit: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR target: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR target PA: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR reason: not requested" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR current EL/SPx sync instruction: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR current EL/SPx sync hint: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR follow-up exit observed: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR follow-up exit: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR follow-up exit reason name: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR follow-up classification: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR follow-up PC: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR follow-up VBAR_EL1: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR follow-up target still set: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR resume original PC: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR resume original ELR_EL1: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR resume original ESR_EL1: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR resume original FAR_EL1: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR resume original SPSR_EL1: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Guest RAM bytes: 0x4000000" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Platform DTB bytes: 0x" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Platform DTB magic: 0xd00dfeed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Platform DTB magic verified: true" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Requested exits: 8" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Observed exits: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Watchdog timeout ms: 100" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "VTimer offset value: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "CNTV_CVAL_EL0 value: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "CNTV_CTL_EL0 value: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "VTimer exit count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Pending IRQ injected count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Device IRQ line asserted count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Device IRQ line deasserted count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Handled MMIO read count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Handled MMIO write count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Handled PL011 MMIO count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Handled PL031 MMIO count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Handled GICD MMIO count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Handled GICR MMIO count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Handled VirtIO installer ISO MMIO count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Handled VirtIO target disk MMIO count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "VirtIO queue_notify count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "VirtIO request completion count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Handled ICC read count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Handled ICC write count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Handled ICC_IAR1 read count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Handled ICC_EOIR1 write count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Handled ICC_DIR write count: 0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Last ICC_IAR1 INTID: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Last ICC_EOIR1 INTID: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Last ICC_DIR INTID: not observed" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Firmware source bytes: 0x20000" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Vars source bytes: 0x10000" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Installer ISO path: $ISO" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Writable target disk path: $DISK" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Firmware block devices:" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "- role=installer-iso, label=VirtIO-MMIO installer ISO, node=virtio_mmio@10002000, base=0x10002000, bytes=0x1000, read_only=true, backing_kind=host-iso-readonly, backing_path=$ISO, device_features=0x20" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "- role=target-disk, label=VirtIO-MMIO target disk, node=virtio_mmio@10003000, base=0x10003000, bytes=0x1000, read_only=false, backing_kind=host-file-writable, backing_path=$DISK, device_features=0x0" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low firmware alias map flags: read|exec" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vars alias map flags: read|write" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Guest RAM map flags: read|write|exec" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low pflash alias requested: false" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "VM create status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low firmware alias map status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vars alias map status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Guest RAM allocate status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "X0 DTB IPA set status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page resume ELR_EL1 set status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page resume SPSR_EL1 set status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page resume CPSR set status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Low vector diagnostic page resume PC set status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR set status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR resume ELR_EL1 set status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR resume VBAR_EL1 set status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR resume SPSR_EL1 set status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Recommended vector-base VBAR resume PC set status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "VTimer offset set status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "CNTV_CVAL_EL0 set status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "CNTV_CTL_EL0 set status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "VTimer initial unmask status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Last pending IRQ set status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Last device IRQ line assert status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Last device IRQ line deassert status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Last VTimer unmask status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Final PC status name: not attempted" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Run-loop exits:" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "- none" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "Blockers:" "Windows Arm firmware run-loop runner output"
assert_contains "$output" "set BRIDGEVM_HVF_ALLOW_UEFI_FIRMWARE_RUN_LOOP=1 or pass --allow-loop" "Windows Arm firmware run-loop runner output"
assert_not_contains "$output" "qemu-system" "Windows Arm firmware run-loop runner output"
assert_not_matches "$output" '[0-9]+([.][0-9]+)?%' "Windows Arm firmware run-loop runner output"
[[ -f "$VARS" ]] || fail "expected mutable vars file to be created"
cmp -s "$VARS_TEMPLATE" "$VARS" || fail "created vars store does not match template"

continue_output="$(cargo run -q -p hvf-runner -- --windows-firmware-run-loop-probe --firmware "$FIRMWARE" --vars-template "$VARS_TEMPLATE" --vars "$CONTINUE_VARS" --create-vars --iso "$ISO" --writable-disk "$DISK" --map-low-pflash-alias --repair-low-vector-diagnostic-page --continue-after-low-vector-repair --remap-low-vector-to-recommended-vector 2>&1)" \
  || fail "hvf-runner --windows-firmware-run-loop-probe continue command failed: $continue_output"

assert_contains "$continue_output" "Windows 11 Arm HVF UEFI firmware run-loop probe" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Allowed: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Attempted: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Run loop attempted: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low pflash alias requested: true" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low firmware alias mapped: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vars alias mapped: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page repair requested: true" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page repaired: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page slot restored: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page restore before ERET requested: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page restore before ERET attempted: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page entry IPA: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page previous descriptor: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page descriptor: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page repeated fault observed: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector recommended-vector remap requested: true" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector recommended-vector remap attempted: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector recommended-vector remap succeeded: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector recommended-vector remap target PA: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector recommended-vector remap descriptor: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Continue after low-vector repair requested: true" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Continue after low-vector repair attempted: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair unsupported exit observed: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair unsupported exit reason name: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair unsupported exit classification: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first exit access kind: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first exit access direction: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first exit access address: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first exit access sysreg: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first exit access syndrome: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first device interaction observed: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first device interaction: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first device interaction reason name: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first device interaction classification: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first device interaction PC: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first device interaction access kind: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first device interaction access direction: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first device interaction access address: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first device interaction access sysreg: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first device interaction access syndrome: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first device interaction kind: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first unhandled access observed: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first unhandled access: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first unhandled access reason name: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first unhandled access classification: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first unhandled access kind: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first unhandled access direction: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first unhandled access handler result: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first unhandled access MMIO device kind: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Post-repair first unhandled access sysreg name: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page resume attempted: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page resume armed: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page resume original PC: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page resume original ELR_EL1: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page resume original ESR_EL1: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page resume original FAR_EL1: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page resume original SPSR_EL1: not observed" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Recommended vector-base VBAR requested: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Recommended vector-base VBAR attempted: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Recommended vector-base VBAR set: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Recommended vector-base VBAR diagnostic vector populated: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Recommended vector-base VBAR resume requested: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Recommended vector-base VBAR resume attempted: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Recommended vector-base VBAR resume armed: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Recommended vector-base VBAR reason: not requested" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Recommended vector-base VBAR follow-up exit observed: false" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page resume ELR_EL1 set status name: not attempted" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page resume SPSR_EL1 set status name: not attempted" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page resume CPSR set status name: not attempted" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Low vector diagnostic page resume PC set status name: not attempted" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "Blockers:" "Windows Arm firmware run-loop runner continue output"
assert_contains "$continue_output" "set BRIDGEVM_HVF_ALLOW_UEFI_FIRMWARE_RUN_LOOP=1 or pass --allow-loop" "Windows Arm firmware run-loop runner continue output"
assert_not_contains "$continue_output" "qemu-system" "Windows Arm firmware run-loop runner continue output"
assert_not_matches "$continue_output" '[0-9]+([.][0-9]+)?%' "Windows Arm firmware run-loop runner continue output"
[[ -f "$CONTINUE_VARS" ]] || fail "expected continue mutable vars file to be created"
cmp -s "$VARS_TEMPLATE" "$CONTINUE_VARS" || fail "created continue vars store does not match template"
assert_no_backend_launch

echo "PASS: Windows 11 Arm no-QEMU HVF firmware run-loop runner smoke ($STORE)"
