//! Fallback backend for hosts that are not macOS/aarch64.
//!
//! Moved verbatim out of the inline `mod platform` block in lib.rs. Contains no
//! `unsafe`: every probe returns a fully-defaulted, fail-closed result.

use crate::{
    recommended_vector_base_vbar_initial_reason, windows_arm_diagnostic_vector_selection,
    windows_arm_firmware_block_devices, windows_arm_firmware_run_loop_dtb_metadata,
    HvfGuestEntryProbe, HvfGuestExitLoopProbe, HvfHostCapabilities, HvfInterruptTimerProbe,
    HvfMemoryMapProbe, HvfMmioBlockDeviceProbe, HvfMmioBlockQueueProbe, HvfMmioBlockQueueStepProbe,
    HvfMmioBlockRegisterProbe, HvfMmioReadEmulationProbe, HvfMmioReadExitProbe,
    HvfMmioRtcDeviceProbe, HvfMmioSerialDeviceProbe, HvfMmioWriteEmulationProbe,
    HvfVcpuCreateProbe, HvfVcpuRunProbe, HvfVmCreateProbe, HvfVtimerExitProbe,
    LowVectorPostRepairTelemetry, WindowsArmUefiFirmwareRunLoopExecutionOptions,
    WindowsArmUefiFirmwareRunLoopProbe, WindowsArmUefiPflashHvfMapProbe,
    WindowsArmUefiPflashMapProbe, WindowsArmUefiResetVectorEntryProbe,
    BLOCK_QUEUE_MMIO_DEVICE_MODELS, BOOT_MMIO_DEVICE_MODELS, PL011_UART_MODEL,
    VIRTIO_MMIO_BLOCK_CAPACITY_SECTORS, VIRTIO_MMIO_BLOCK_CONFIG_GENERATION_VALUE,
    VIRTIO_MMIO_BLOCK_DEVICE_FEATURES_VALUE, VIRTIO_MMIO_BLOCK_DEVICE_ID_VALUE,
    VIRTIO_MMIO_BLOCK_DRIVER_FEATURES_VALUE, VIRTIO_MMIO_BLOCK_QUEUE_DESC_ADDRESS,
    VIRTIO_MMIO_BLOCK_QUEUE_DEVICE_ADDRESS, VIRTIO_MMIO_BLOCK_QUEUE_DRIVER_ADDRESS,
    VIRTIO_MMIO_BLOCK_QUEUE_NOTIFY_VALUE, VIRTIO_MMIO_BLOCK_QUEUE_NUM_MAX_VALUE,
    VIRTIO_MMIO_BLOCK_QUEUE_NUM_VALUE, VIRTIO_MMIO_BLOCK_QUEUE_READY_VALUE,
    VIRTIO_MMIO_BLOCK_QUEUE_SEL_VALUE, VIRTIO_MMIO_BLOCK_STATUS_ACK_VALUE,
    VIRTIO_MMIO_BLOCK_STATUS_DRIVER_VALUE, VIRTIO_MMIO_BLOCK_STATUS_FEATURES_OK_VALUE,
    VIRTIO_MMIO_BLOCK_STATUS_VALUE, VIRTIO_MMIO_INTERRUPT_USED_BUFFER_VALUE,
    VIRTIO_MMIO_MAGIC_VALUE, VIRTIO_MMIO_VENDOR_ID_VALUE, VIRTIO_MMIO_VERSION_VALUE,
    WINDOWS_ARM_DIAGNOSTIC_VECTOR_BYTES, WINDOWS_ARM_DIAGNOSTIC_VECTOR_IPA,
    WINDOWS_ARM_EXECUTABLE_DIAGNOSTIC_VECTOR_IPA, WINDOWS_ARM_GUEST_RAM_DIAGNOSTIC_VECTOR_IPA,
    WINDOWS_ARM_GUEST_RAM_IPA, WINDOWS_ARM_PLATFORM_DTB_GUEST_RAM_OFFSET,
    WINDOWS_ARM_PLATFORM_DTB_IPA, WINDOWS_ARM_UEFI_CODE_IPA, WINDOWS_ARM_UEFI_LOW_CODE_ALIAS_IPA,
    WINDOWS_ARM_UEFI_LOW_VARS_ALIAS_IPA, WINDOWS_ARM_UEFI_SLOT_BYTES, WINDOWS_ARM_UEFI_VARS_IPA,
};
use std::path::PathBuf;

pub fn query_hvf_host_capabilities() -> HvfHostCapabilities {
    HvfHostCapabilities {
        available: false,
        host: "unsupported",
        default_ipa_bits: None,
        max_ipa_bits: None,
        el2_supported: None,
        blockers: vec![
            "Apple Hypervisor.framework Arm VM configuration is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_windows_11_arm_uefi_firmware_run_loop(
    options: WindowsArmUefiFirmwareRunLoopExecutionOptions,
    pflash_map: WindowsArmUefiPflashMapProbe,
    host: HvfHostCapabilities,
) -> WindowsArmUefiFirmwareRunLoopProbe {
    let WindowsArmUefiFirmwareRunLoopExecutionOptions {
        allow_loop,
        requested_exits,
        guest_ram_mib,
        watchdog_timeout_ms,
        map_low_pflash_alias,
        seed_diagnostic_vector,
        seed_guest_ram_diagnostic_vector,
        seed_executable_diagnostic_vector,
        try_recommended_vector_base_vbar,
        continue_after_recommended_vector_base_vbar,
        repair_low_vector_diagnostic_page,
        remap_low_vector_to_recommended_vector: _,
        continue_after_low_vector_repair,
        restore_low_vector_slot_before_eret: _,
        wire_interrupt_timer,
        stop_at_first_post_repair_device_boundary,
        installer_iso_path,
        writable_target_disk_path,
    } = options.clone();
    let mut blockers = pflash_map.blockers.clone();
    if !allow_loop {
        blockers.push(
            "set BRIDGEVM_HVF_ALLOW_UEFI_FIRMWARE_RUN_LOOP=1 or pass --allow-loop to map Windows UEFI pflash plus guest RAM, create one vCPU, and classify bounded firmware exits under a watchdog".to_string(),
        );
    }
    blockers.push(
        "Apple Hypervisor.framework Windows UEFI firmware run-loop probe is only available on Apple Silicon macOS".to_string(),
    );
    let guest_ram_bytes = u64::from(guest_ram_mib.clamp(1, 4096)) * 1024 * 1024;
    let block_devices = windows_arm_firmware_block_devices(
        installer_iso_path.clone(),
        writable_target_disk_path.clone(),
    );
    let (platform_dtb_bytes, platform_dtb_magic, platform_dtb_magic_verified) =
        windows_arm_firmware_run_loop_dtb_metadata(guest_ram_bytes);
    let diagnostic_vector = windows_arm_diagnostic_vector_selection(
        seed_diagnostic_vector,
        seed_guest_ram_diagnostic_vector,
        seed_executable_diagnostic_vector,
    );
    let diagnostic_vector_seed_requested = diagnostic_vector.requested;
    let recommended_vector_base_vbar_reason = recommended_vector_base_vbar_initial_reason(
        try_recommended_vector_base_vbar,
        diagnostic_vector_seed_requested,
        repair_low_vector_diagnostic_page,
    );
    let low_vector_post_repair = LowVectorPostRepairTelemetry::default();
    WindowsArmUefiFirmwareRunLoopProbe {
        allowed: allow_loop,
        attempted: false,
        vm_created: false,
        firmware_memory_allocated: false,
        vars_memory_allocated: false,
        guest_ram_memory_allocated: false,
        firmware_memory_populated: false,
        vars_memory_populated: false,
        firmware_memory_mapped: false,
        vars_memory_mapped: false,
        low_firmware_alias_mapped: false,
        low_vars_alias_mapped: false,
        guest_ram_memory_mapped: false,
        platform_dtb_populated: false,
        diagnostic_vector_seed_requested,
        diagnostic_vector_populated: false,
        low_vector_diagnostic_page_repair_requested: repair_low_vector_diagnostic_page,
        low_vector_diagnostic_page_repaired: false,
        low_vector_diagnostic_page_slot_restored: false,
        low_vector_diagnostic_page_restore_before_eret_requested: options
            .restore_low_vector_slot_before_eret,
        low_vector_diagnostic_page_restore_before_eret_attempted: false,
        low_vector_diagnostic_page_entry_ipa: None,
        low_vector_diagnostic_page_previous_descriptor: None,
        low_vector_diagnostic_page_descriptor: None,
        low_vector_diagnostic_page_repeated_fault_observed: false,
        low_vector_recommended_vector_remap_requested: options
            .remap_low_vector_to_recommended_vector,
        low_vector_recommended_vector_remap_attempted: false,
        low_vector_recommended_vector_remap_succeeded: false,
        low_vector_recommended_vector_remap_target_physical_address: None,
        low_vector_recommended_vector_remap_descriptor: None,
        low_vector_post_repair_continue_requested: continue_after_low_vector_repair,
        low_vector_post_repair_continue_attempted: low_vector_post_repair.continue_attempted,
        stop_at_first_post_repair_device_boundary_requested:
            stop_at_first_post_repair_device_boundary,
        low_vector_post_repair_unsupported_exit_observed: low_vector_post_repair
            .unsupported_exit_observed,
        low_vector_post_repair_unsupported_exit_reason: low_vector_post_repair
            .unsupported_exit_reason,
        low_vector_post_repair_unsupported_exit_diagnosis: low_vector_post_repair
            .unsupported_exit_diagnosis,
        low_vector_post_repair_first_exit_observed: low_vector_post_repair.first_exit.observed,
        low_vector_post_repair_first_exit_index: low_vector_post_repair.first_exit.index,
        low_vector_post_repair_first_exit_reason: low_vector_post_repair.first_exit.reason,
        low_vector_post_repair_first_exit_diagnosis: low_vector_post_repair.first_exit.diagnosis,
        low_vector_post_repair_first_exit_pc: low_vector_post_repair.first_exit.pc,
        low_vector_post_repair_first_interaction_kind: low_vector_post_repair
            .first_exit
            .interaction_kind,
        low_vector_post_repair_first_exit_access_kind: low_vector_post_repair
            .first_exit
            .access
            .kind,
        low_vector_post_repair_first_exit_access_direction: low_vector_post_repair
            .first_exit
            .access
            .direction,
        low_vector_post_repair_first_exit_access_address: low_vector_post_repair
            .first_exit
            .access
            .address,
        low_vector_post_repair_first_exit_access_sysreg: low_vector_post_repair
            .first_exit
            .access
            .sysreg,
        low_vector_post_repair_first_exit_access_syndrome: low_vector_post_repair
            .first_exit
            .access
            .syndrome,
        low_vector_post_repair_first_device_interaction_observed: low_vector_post_repair
            .first_device_interaction
            .observed,
        low_vector_post_repair_first_device_interaction_index: low_vector_post_repair
            .first_device_interaction
            .index,
        low_vector_post_repair_first_device_interaction_reason: low_vector_post_repair
            .first_device_interaction
            .reason,
        low_vector_post_repair_first_device_interaction_diagnosis: low_vector_post_repair
            .first_device_interaction
            .diagnosis,
        low_vector_post_repair_first_device_interaction_pc: low_vector_post_repair
            .first_device_interaction
            .pc,
        low_vector_post_repair_first_device_interaction_kind: low_vector_post_repair
            .first_device_interaction
            .interaction_kind,
        low_vector_post_repair_first_device_interaction_access_kind: low_vector_post_repair
            .first_device_interaction
            .access
            .kind,
        low_vector_post_repair_first_device_interaction_access_direction: low_vector_post_repair
            .first_device_interaction
            .access
            .direction,
        low_vector_post_repair_first_device_interaction_access_address: low_vector_post_repair
            .first_device_interaction
            .access
            .address,
        low_vector_post_repair_first_device_interaction_access_sysreg: low_vector_post_repair
            .first_device_interaction
            .access
            .sysreg,
        low_vector_post_repair_first_device_interaction_access_syndrome: low_vector_post_repair
            .first_device_interaction
            .access
            .syndrome,
        low_vector_post_repair_first_unhandled_access_observed: low_vector_post_repair
            .first_unhandled_access
            .observed,
        low_vector_post_repair_first_unhandled_access_index: low_vector_post_repair
            .first_unhandled_access
            .index,
        low_vector_post_repair_first_unhandled_access_reason: low_vector_post_repair
            .first_unhandled_access
            .reason,
        low_vector_post_repair_first_unhandled_access_diagnosis: low_vector_post_repair
            .first_unhandled_access
            .diagnosis,
        low_vector_post_repair_first_unhandled_access_pc: low_vector_post_repair
            .first_unhandled_access
            .pc,
        low_vector_post_repair_first_unhandled_access_syndrome: low_vector_post_repair
            .first_unhandled_access
            .syndrome,
        low_vector_post_repair_first_unhandled_access_kind: low_vector_post_repair
            .first_unhandled_access
            .kind,
        low_vector_post_repair_first_unhandled_access_direction: low_vector_post_repair
            .first_unhandled_access
            .access,
        low_vector_post_repair_first_unhandled_access_register: low_vector_post_repair
            .first_unhandled_access
            .register,
        low_vector_post_repair_first_unhandled_access_value: low_vector_post_repair
            .first_unhandled_access
            .value,
        low_vector_post_repair_first_unhandled_access_handler_result: low_vector_post_repair
            .first_unhandled_access
            .handler_result,
        low_vector_post_repair_first_unhandled_access_mmio_ipa: low_vector_post_repair
            .first_unhandled_access
            .mmio_ipa,
        low_vector_post_repair_first_unhandled_access_mmio_width: low_vector_post_repair
            .first_unhandled_access
            .mmio_width,
        low_vector_post_repair_first_unhandled_access_mmio_device_kind: low_vector_post_repair
            .first_unhandled_access
            .mmio_device_kind,
        low_vector_post_repair_first_unhandled_access_sysreg: low_vector_post_repair
            .first_unhandled_access
            .sysreg,
        low_vector_post_repair_first_unhandled_access_sysreg_name: low_vector_post_repair
            .first_unhandled_access
            .sysreg_name,
        low_vector_post_repair_first_unhandled_access_sysreg_op0: low_vector_post_repair
            .first_unhandled_access
            .sysreg_op0,
        low_vector_post_repair_first_unhandled_access_sysreg_op1: low_vector_post_repair
            .first_unhandled_access
            .sysreg_op1,
        low_vector_post_repair_first_unhandled_access_sysreg_crn: low_vector_post_repair
            .first_unhandled_access
            .sysreg_crn,
        low_vector_post_repair_first_unhandled_access_sysreg_crm: low_vector_post_repair
            .first_unhandled_access
            .sysreg_crm,
        low_vector_post_repair_first_unhandled_access_sysreg_op2: low_vector_post_repair
            .first_unhandled_access
            .sysreg_op2,
        low_vector_diagnostic_page_resume_attempted: false,
        low_vector_diagnostic_page_resume_armed: false,
        low_vector_diagnostic_page_resume_original_pc: None,
        low_vector_diagnostic_page_resume_original_elr_el1: None,
        low_vector_diagnostic_page_resume_original_esr_el1: None,
        low_vector_diagnostic_page_resume_original_far_el1: None,
        low_vector_diagnostic_page_resume_original_spsr_el1: None,
        low_vector_diagnostic_page_original_slot_bytes: None,
        low_vector_diagnostic_page_resume_target_instruction_before_eret: None,
        low_vector_diagnostic_page_resume_target_stage1_leaf_descriptor_before_eret: None,
        low_vector_diagnostic_page_resume_target_stage1_leaf_kind_before_eret: "not observed",
        low_vector_diagnostic_page_resume_target_is_installed_diagnostic_hvc_before_eret: false,
        low_vector_diagnostic_page_resume_elr_el1_set_status: None,
        low_vector_diagnostic_page_resume_spsr_el1_set_status: None,
        low_vector_diagnostic_page_resume_cpsr_set_status: None,
        low_vector_diagnostic_page_resume_pc_set_status: None,
        vcpu_created: false,
        pc_set: false,
        x0_dtb_ipa_set: false,
        cpsr_set: false,
        sp_el1_set: false,
        diagnostic_vector_vbar_el1_set: false,
        recommended_vector_base_vbar_requested: try_recommended_vector_base_vbar,
        recommended_vector_base_vbar_attempted: false,
        recommended_vector_base_vbar_set: false,
        recommended_vector_base_vbar_diagnostic_vector_populated: false,
        recommended_vector_base_vbar_resume_requested: continue_after_recommended_vector_base_vbar,
        recommended_vector_base_vbar_resume_attempted: false,
        recommended_vector_base_vbar_resume_armed: false,
        interrupt_timer_wiring_requested: wire_interrupt_timer,
        interrupt_timer_initialized: false,
        run_loop_attempted: false,
        firmware_progress_observed: false,
        unsupported_exit_observed: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        firmware_memory_unmapped: false,
        vars_memory_unmapped: false,
        guest_ram_memory_unmapped: false,
        firmware_memory_deallocated: false,
        vars_memory_deallocated: false,
        guest_ram_memory_deallocated: false,
        vm_destroyed: false,
        host,
        pflash_map_verified: pflash_map.pflash_map_verified,
        reset_vector_ipa: WINDOWS_ARM_UEFI_CODE_IPA,
        firmware_slot_ipa: WINDOWS_ARM_UEFI_CODE_IPA,
        vars_slot_ipa: WINDOWS_ARM_UEFI_VARS_IPA,
        low_firmware_alias_ipa: WINDOWS_ARM_UEFI_LOW_CODE_ALIAS_IPA,
        low_vars_alias_ipa: WINDOWS_ARM_UEFI_LOW_VARS_ALIAS_IPA,
        guest_ram_ipa: WINDOWS_ARM_GUEST_RAM_IPA,
        platform_dtb_ipa: WINDOWS_ARM_PLATFORM_DTB_IPA,
        platform_dtb_guest_ram_offset: WINDOWS_ARM_PLATFORM_DTB_GUEST_RAM_OFFSET,
        sp_el1_seed_ipa: crate::windows_arm_initial_sp_el1_ipa(guest_ram_bytes),
        diagnostic_vector_location: diagnostic_vector.location,
        diagnostic_vector_ipa: diagnostic_vector.ipa,
        diagnostic_vector_bytes: WINDOWS_ARM_DIAGNOSTIC_VECTOR_BYTES,
        recommended_vector_base_vbar_source_exit_index: None,
        recommended_vector_base_vbar_target: None,
        recommended_vector_base_vbar_target_physical_address: None,
        recommended_vector_base_vbar_reason,
        recommended_vector_base_vbar_current_el_spx_sync_instruction_word: None,
        recommended_vector_base_vbar_current_el_spx_sync_instruction_hint: "not observed",
        recommended_vector_base_vbar_followup_exit_observed: false,
        recommended_vector_base_vbar_followup_exit_index: None,
        recommended_vector_base_vbar_followup_exit_reason: None,
        recommended_vector_base_vbar_followup_exit_diagnosis: "not observed",
        recommended_vector_base_vbar_followup_pc: None,
        recommended_vector_base_vbar_followup_vbar_el1: None,
        recommended_vector_base_vbar_followup_target_still_set: false,
        recommended_vector_base_vbar_resume_original_pc: None,
        recommended_vector_base_vbar_resume_original_elr_el1: None,
        recommended_vector_base_vbar_resume_original_esr_el1: None,
        recommended_vector_base_vbar_resume_original_far_el1: None,
        recommended_vector_base_vbar_resume_original_spsr_el1: None,
        slot_bytes: WINDOWS_ARM_UEFI_SLOT_BYTES,
        guest_ram_bytes,
        platform_dtb_bytes,
        platform_dtb_magic,
        platform_dtb_magic_verified,
        requested_exits: requested_exits.clamp(1, 64),
        observed_exits: 0,
        watchdog_timeout_ms: watchdog_timeout_ms.clamp(1, 60_000),
        vtimer_offset_value: wire_interrupt_timer.then_some(0x1000),
        cntv_cval_value: wire_interrupt_timer.then_some(0),
        cntv_ctl_value: wire_interrupt_timer.then_some(1),
        vtimer_exit_count: 0,
        pending_irq_injected_count: 0,
        device_irq_injected_count: 0,
        device_irq_cleared_count: 0,
        handled_mmio_read_count: 0,
        handled_mmio_write_count: 0,
        handled_pl011_mmio_count: 0,
        handled_pl031_mmio_count: 0,
        handled_gicd_mmio_count: 0,
        handled_gicr_mmio_count: 0,
        handled_virtio_installer_iso_mmio_count: 0,
        handled_virtio_target_disk_mmio_count: 0,
        virtio_queue_notify_count: 0,
        virtio_request_completion_count: 0,
        handled_icc_read_count: 0,
        handled_icc_write_count: 0,
        handled_icc_iar1_read_count: 0,
        handled_icc_eoir1_write_count: 0,
        handled_icc_dir_write_count: 0,
        last_icc_iar1_intid: None,
        last_icc_eoir1_intid: None,
        last_icc_dir_intid: None,
        firmware_source_bytes: pflash_map
            .firmware_slot
            .as_ref()
            .map(|slot| slot.source_bytes),
        vars_source_bytes: pflash_map.vars_slot.as_ref().map(|slot| slot.source_bytes),
        installer_iso_path,
        writable_target_disk_path,
        block_devices,
        firmware_map_flags: "read|exec",
        vars_map_flags: "read|write",
        low_firmware_alias_map_flags: "read|exec",
        low_vars_alias_map_flags: "read|write",
        guest_ram_map_flags: "read|write|exec",
        low_pflash_alias_requested: map_low_pflash_alias,
        vm_create_status: None,
        firmware_allocate_status: None,
        vars_allocate_status: None,
        guest_ram_allocate_status: None,
        firmware_map_status: None,
        vars_map_status: None,
        low_firmware_alias_map_status: None,
        low_vars_alias_map_status: None,
        guest_ram_map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        x0_dtb_ipa_set_status: None,
        cpsr_set_status: None,
        sp_el1_set_status: None,
        diagnostic_vector_vbar_el1_set_status: None,
        recommended_vector_base_vbar_set_status: None,
        recommended_vector_base_vbar_resume_vbar_el1_set_status: None,
        recommended_vector_base_vbar_resume_elr_el1_set_status: None,
        recommended_vector_base_vbar_resume_spsr_el1_set_status: None,
        recommended_vector_base_vbar_resume_pc_set_status: None,
        vtimer_offset_set_status: None,
        cntv_cval_set_status: None,
        cntv_ctl_set_status: None,
        vtimer_initial_unmask_status: None,
        last_pending_irq_set_status: None,
        last_device_irq_set_status: None,
        last_device_irq_clear_status: None,
        last_vtimer_unmask_status: None,
        final_pc_status: None,
        final_pc: None,
        vcpu_destroy_status: None,
        firmware_unmap_status: None,
        vars_unmap_status: None,
        low_firmware_alias_unmap_status: None,
        low_vars_alias_unmap_status: None,
        guest_ram_unmap_status: None,
        firmware_deallocate_status: None,
        vars_deallocate_status: None,
        guest_ram_deallocate_status: None,
        vm_destroy_status: None,
        exits: Vec::new(),
        blockers,
    }
}

pub fn probe_hvf_vm_create(allow_create: bool, host: HvfHostCapabilities) -> HvfVmCreateProbe {
    HvfVmCreateProbe {
        allowed: allow_create,
        attempted: false,
        created: false,
        destroyed: false,
        host,
        create_status: None,
        destroy_status: None,
        blockers: vec![
            "Apple Hypervisor.framework VM create/destroy probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_vcpu_create(allow_create: bool, host: HvfHostCapabilities) -> HvfVcpuCreateProbe {
    HvfVcpuCreateProbe {
        allowed: allow_create,
        attempted: false,
        vm_created: false,
        vcpu_created: false,
        vcpu_destroyed: false,
        vm_destroyed: false,
        host,
        vm_create_status: None,
        vcpu_create_status: None,
        vcpu_destroy_status: None,
        vm_destroy_status: None,
        blockers: vec![
            "Apple Hypervisor.framework vCPU create/destroy probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_vcpu_run(allow_run: bool, host: HvfHostCapabilities) -> HvfVcpuRunProbe {
    HvfVcpuRunProbe {
        allowed: allow_run,
        attempted: false,
        vm_created: false,
        vcpu_created: false,
        cancel_requested: false,
        run_attempted: false,
        run_boundary_observed: false,
        vcpu_destroyed: false,
        vm_destroyed: false,
        host,
        vm_create_status: None,
        vcpu_create_status: None,
        cancel_status: None,
        run_status: None,
        exit_reason: None,
        vcpu_destroy_status: None,
        vm_destroy_status: None,
        blockers: vec![
            "Apple Hypervisor.framework vCPU run/cancel probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_interrupt_timer(
    allow_probe: bool,
    host: HvfHostCapabilities,
) -> HvfInterruptTimerProbe {
    HvfInterruptTimerProbe {
        allowed: allow_probe,
        attempted: false,
        vm_created: false,
        vcpu_created: false,
        pending_irq_set: false,
        pending_irq_cleared: false,
        vtimer_masked: false,
        vtimer_unmasked: false,
        vtimer_offset_set: false,
        boundary_observed: false,
        vcpu_destroyed: false,
        vm_destroyed: false,
        host,
        vtimer_offset_value: 0x1000,
        vm_create_status: None,
        vcpu_create_status: None,
        irq_set_status: None,
        irq_get_after_set_status: None,
        irq_pending_after_set: None,
        irq_clear_status: None,
        irq_get_after_clear_status: None,
        irq_pending_after_clear: None,
        vtimer_mask_set_status: None,
        vtimer_mask_get_status: None,
        vtimer_mask_after_set: None,
        vtimer_unmask_status: None,
        vtimer_unmask_get_status: None,
        vtimer_mask_after_clear: None,
        vtimer_offset_set_status: None,
        vtimer_offset_get_status: None,
        vtimer_offset_after_set: None,
        vcpu_destroy_status: None,
        vm_destroy_status: None,
        blockers: vec![
            "Apple Hypervisor.framework interrupt/timer probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_vtimer_exit(allow_probe: bool, host: HvfHostCapabilities) -> HvfVtimerExitProbe {
    HvfVtimerExitProbe {
        allowed: allow_probe,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        vtimer_offset_set: false,
        cntv_cval_set: false,
        cntv_ctl_set: false,
        vtimer_unmasked: false,
        run_attempted: false,
        vtimer_exit_observed: false,
        pending_irq_injected: false,
        vtimer_mask_observed_after_exit: None,
        vtimer_unmasked_after_exit: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        ipa_start: 0x4000_0000,
        bytes: 16 * 1024,
        instructions: "WFI; HVC #0",
        vtimer_offset_value: 0,
        cntv_cval_value: 0,
        cntv_ctl_value: 1,
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        vtimer_offset_set_status: None,
        cntv_cval_set_status: None,
        cntv_ctl_set_status: None,
        vtimer_unmask_status: None,
        run_status: None,
        exit_reason: None,
        exit_syndrome: None,
        exit_virtual_address: None,
        exit_physical_address: None,
        watchdog_cancel_status: None,
        pending_irq_set_status: None,
        vtimer_mask_get_after_exit_status: None,
        vtimer_unmask_after_exit_status: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework VTimer exit probe is only available on Apple Silicon macOS"
                .to_string(),
        ],
    }
}

pub fn probe_hvf_memory_map(allow_map: bool, host: HvfHostCapabilities) -> HvfMemoryMapProbe {
    HvfMemoryMapProbe {
        allowed: allow_map,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        memory_unmapped: false,
        memory_deallocated: false,
        vm_destroyed: false,
        host,
        ipa_start: 0x4000_0000,
        bytes: 16 * 1024,
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        unmap_status: None,
        deallocate_status: None,
        vm_destroy_status: None,
        blockers: vec![
            "Apple Hypervisor.framework memory map/unmap probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_windows_11_arm_uefi_pflash_hvf_map(
    allow_map: bool,
    pflash_map: WindowsArmUefiPflashMapProbe,
    host: HvfHostCapabilities,
) -> WindowsArmUefiPflashHvfMapProbe {
    let mut blockers = pflash_map.blockers.clone();
    if !allow_map {
        blockers.push(
            "set BRIDGEVM_HVF_ALLOW_UEFI_PFLASH_MAP=1 or pass --allow-map to create an empty HVF VM and map/unmap Windows UEFI code/vars pflash slots".to_string(),
        );
    }
    blockers.push(
        "Apple Hypervisor.framework Windows UEFI pflash map/unmap probe is only available on Apple Silicon macOS".to_string(),
    );
    WindowsArmUefiPflashHvfMapProbe {
        allowed: allow_map,
        attempted: false,
        vm_created: false,
        firmware_memory_allocated: false,
        vars_memory_allocated: false,
        firmware_memory_populated: false,
        vars_memory_populated: false,
        firmware_memory_mapped: false,
        vars_memory_mapped: false,
        firmware_memory_unmapped: false,
        vars_memory_unmapped: false,
        firmware_memory_deallocated: false,
        vars_memory_deallocated: false,
        vm_destroyed: false,
        host,
        pflash_map_verified: pflash_map.pflash_map_verified,
        firmware_slot_ipa: WINDOWS_ARM_UEFI_CODE_IPA,
        vars_slot_ipa: WINDOWS_ARM_UEFI_VARS_IPA,
        slot_bytes: WINDOWS_ARM_UEFI_SLOT_BYTES,
        firmware_source_bytes: pflash_map
            .firmware_slot
            .as_ref()
            .map(|slot| slot.source_bytes),
        vars_source_bytes: pflash_map.vars_slot.as_ref().map(|slot| slot.source_bytes),
        firmware_map_flags: "read|exec",
        vars_map_flags: "read|write",
        vm_create_status: None,
        firmware_allocate_status: None,
        vars_allocate_status: None,
        firmware_map_status: None,
        vars_map_status: None,
        firmware_unmap_status: None,
        vars_unmap_status: None,
        firmware_deallocate_status: None,
        vars_deallocate_status: None,
        vm_destroy_status: None,
        blockers,
    }
}

pub fn probe_windows_11_arm_uefi_reset_vector_entry(
    allow_entry: bool,
    pflash_map: WindowsArmUefiPflashMapProbe,
    host: HvfHostCapabilities,
) -> WindowsArmUefiResetVectorEntryProbe {
    let mut blockers = pflash_map.blockers.clone();
    if !allow_entry {
        blockers.push(
            "set BRIDGEVM_HVF_ALLOW_UEFI_RESET_VECTOR_ENTRY=1 or pass --allow-entry to map Windows UEFI pflash slots, create one vCPU, set PC to the reset vector, and run once under a watchdog".to_string(),
        );
    }
    blockers.push(
        "Apple Hypervisor.framework Windows UEFI reset-vector entry probe is only available on Apple Silicon macOS".to_string(),
    );
    WindowsArmUefiResetVectorEntryProbe {
        allowed: allow_entry,
        attempted: false,
        vm_created: false,
        firmware_memory_allocated: false,
        vars_memory_allocated: false,
        firmware_memory_populated: false,
        vars_memory_populated: false,
        firmware_memory_mapped: false,
        vars_memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        run_attempted: false,
        reset_vector_entry_observed: false,
        firmware_progress_observed: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        firmware_memory_unmapped: false,
        vars_memory_unmapped: false,
        firmware_memory_deallocated: false,
        vars_memory_deallocated: false,
        vm_destroyed: false,
        host,
        pflash_map_verified: pflash_map.pflash_map_verified,
        reset_vector_ipa: WINDOWS_ARM_UEFI_CODE_IPA,
        firmware_slot_ipa: WINDOWS_ARM_UEFI_CODE_IPA,
        vars_slot_ipa: WINDOWS_ARM_UEFI_VARS_IPA,
        slot_bytes: WINDOWS_ARM_UEFI_SLOT_BYTES,
        firmware_source_bytes: pflash_map
            .firmware_slot
            .as_ref()
            .map(|slot| slot.source_bytes),
        vars_source_bytes: pflash_map.vars_slot.as_ref().map(|slot| slot.source_bytes),
        firmware_map_flags: "read|exec",
        vars_map_flags: "read|write",
        vm_create_status: None,
        firmware_allocate_status: None,
        vars_allocate_status: None,
        firmware_map_status: None,
        vars_map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        run_status: None,
        exit_reason: None,
        exit_syndrome: None,
        exit_exception_class: None,
        exit_virtual_address: None,
        exit_physical_address: None,
        pc_after_run_status: None,
        pc_after_run: None,
        watchdog_cancel_status: None,
        vcpu_destroy_status: None,
        firmware_unmap_status: None,
        vars_unmap_status: None,
        firmware_deallocate_status: None,
        vars_deallocate_status: None,
        vm_destroy_status: None,
        blockers,
    }
}

pub fn probe_hvf_guest_entry(allow_entry: bool, host: HvfHostCapabilities) -> HvfGuestEntryProbe {
    HvfGuestEntryProbe {
        allowed: allow_entry,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        run_attempted: false,
        entry_boundary_observed: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        ipa_start: 0x4000_0000,
        bytes: 16 * 1024,
        instruction: "HVC #0",
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        run_status: None,
        exit_reason: None,
        exit_syndrome: None,
        exit_virtual_address: None,
        exit_physical_address: None,
        watchdog_cancel_status: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework guest entry probe is only available on Apple Silicon macOS"
                .to_string(),
        ],
    }
}

pub fn probe_hvf_guest_exit_loop(
    allow_loop: bool,
    host: HvfHostCapabilities,
) -> HvfGuestExitLoopProbe {
    HvfGuestExitLoopProbe {
        allowed: allow_loop,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        initial_pc_set: false,
        cpsr_set: false,
        first_run_attempted: false,
        first_exit_observed: false,
        pc_read_after_first_exit: false,
        pc_advanced: false,
        second_run_attempted: false,
        second_exit_observed: false,
        exit_loop_observed: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        ipa_start: 0x4000_0000,
        bytes: 16 * 1024,
        instructions: "HVC #0; HVC #1",
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        initial_pc_set_status: None,
        cpsr_set_status: None,
        first_run_status: None,
        first_exit_reason: None,
        first_exit_syndrome: None,
        first_exit_virtual_address: None,
        first_exit_physical_address: None,
        first_watchdog_cancel_status: None,
        pc_read_status: None,
        pc_after_first_exit: None,
        pc_advance_status: None,
        second_run_status: None,
        second_exit_reason: None,
        second_exit_syndrome: None,
        second_exit_virtual_address: None,
        second_exit_physical_address: None,
        second_watchdog_cancel_status: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework guest exit loop probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_mmio_read_exit(
    allow_mmio: bool,
    host: HvfHostCapabilities,
) -> HvfMmioReadExitProbe {
    HvfMmioReadExitProbe {
        allowed: allow_mmio,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        address_register_set: false,
        run_attempted: false,
        mmio_exit_observed: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        device_model: PL011_UART_MODEL,
        code_ipa_start: 0x4000_0000,
        mmio_ipa: 0x5000_0000,
        bytes: 16 * 1024,
        instruction: "LDR X0, [X1]",
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        address_register_set_status: None,
        run_status: None,
        exit_reason: None,
        exit_syndrome: None,
        exit_virtual_address: None,
        exit_physical_address: None,
        watchdog_cancel_status: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework MMIO read exit probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_mmio_read_emulation(
    allow_emulate: bool,
    host: HvfHostCapabilities,
) -> HvfMmioReadEmulationProbe {
    HvfMmioReadEmulationProbe {
        allowed: allow_emulate,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        address_register_set: false,
        first_run_attempted: false,
        mmio_exit_observed: false,
        pc_read_after_mmio_exit: false,
        emulated_value_injected: false,
        pc_advanced: false,
        second_run_attempted: false,
        continuation_exit_observed: false,
        emulated_value_preserved: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        code_ipa_start: 0x4000_0000,
        mmio_ipa: 0x5000_0000,
        bytes: 16 * 1024,
        instructions: "LDR X0, [X1]; HVC #0",
        emulated_value: 0x1234_5678_9abc_def0,
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        address_register_set_status: None,
        first_run_status: None,
        mmio_exit_reason: None,
        mmio_exit_syndrome: None,
        mmio_exit_virtual_address: None,
        mmio_exit_physical_address: None,
        first_watchdog_cancel_status: None,
        pc_read_status: None,
        pc_after_mmio_exit: None,
        emulated_value_set_status: None,
        pc_advance_status: None,
        second_run_status: None,
        continuation_exit_reason: None,
        continuation_exit_syndrome: None,
        continuation_exit_virtual_address: None,
        continuation_exit_physical_address: None,
        second_watchdog_cancel_status: None,
        emulated_value_read_status: None,
        emulated_value_after_continue: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework MMIO read emulation probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_mmio_write_emulation(
    allow_emulate: bool,
    host: HvfHostCapabilities,
) -> HvfMmioWriteEmulationProbe {
    HvfMmioWriteEmulationProbe {
        allowed: allow_emulate,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        write_value_register_set: false,
        address_register_set: false,
        first_run_attempted: false,
        mmio_exit_observed: false,
        pc_read_after_mmio_exit: false,
        write_value_captured: false,
        pc_advanced: false,
        second_run_attempted: false,
        continuation_exit_observed: false,
        write_value_preserved: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        code_ipa_start: 0x4000_0000,
        mmio_ipa: 0x5000_0000,
        bytes: 16 * 1024,
        instructions: "STR X0, [X1]; HVC #0",
        write_value: 0x0fed_cba9_8765_4321,
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        write_value_register_set_status: None,
        address_register_set_status: None,
        first_run_status: None,
        mmio_exit_reason: None,
        mmio_exit_syndrome: None,
        mmio_exit_virtual_address: None,
        mmio_exit_physical_address: None,
        first_watchdog_cancel_status: None,
        pc_read_status: None,
        pc_after_mmio_exit: None,
        write_value_capture_status: None,
        captured_write_value: None,
        pc_advance_status: None,
        second_run_status: None,
        continuation_exit_reason: None,
        continuation_exit_syndrome: None,
        continuation_exit_virtual_address: None,
        continuation_exit_physical_address: None,
        second_watchdog_cancel_status: None,
        write_value_after_continue_status: None,
        write_value_after_continue: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework MMIO write emulation probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_mmio_serial_device(
    allow_device: bool,
    host: HvfHostCapabilities,
) -> HvfMmioSerialDeviceProbe {
    HvfMmioSerialDeviceProbe {
        allowed: allow_device,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        write_value_register_set: false,
        data_address_register_set: false,
        status_address_register_set: false,
        device_bus_created: false,
        device_bus_device_count: 0,
        write_run_attempted: false,
        write_exit_observed: false,
        write_handled_by_device: false,
        write_value_captured: false,
        pc_advanced_after_write: false,
        status_run_attempted: false,
        status_exit_observed: false,
        status_handled_by_device: false,
        status_value_injected: false,
        pc_advanced_after_status: false,
        continuation_run_attempted: false,
        continuation_exit_observed: false,
        status_value_preserved: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        code_ipa_start: 0x4000_0000,
        data_ipa: 0x5000_0000,
        status_ipa: 0x5000_0018,
        bytes: 16 * 1024,
        instructions: "STR X0, [X1]; LDR X0, [X2]; HVC #0",
        serial_write_value: 0x41,
        serial_status_value: 0x90,
        captured_write_value: None,
        captured_byte: None,
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        write_value_register_set_status: None,
        data_address_register_set_status: None,
        status_address_register_set_status: None,
        write_run_status: None,
        write_exit_reason: None,
        write_exit_syndrome: None,
        write_exit_virtual_address: None,
        write_exit_physical_address: None,
        write_watchdog_cancel_status: None,
        write_value_capture_status: None,
        pc_read_after_write_status: None,
        pc_after_write_exit: None,
        pc_advance_after_write_status: None,
        status_run_status: None,
        status_exit_reason: None,
        status_exit_syndrome: None,
        status_exit_virtual_address: None,
        status_exit_physical_address: None,
        status_watchdog_cancel_status: None,
        status_value_set_status: None,
        pc_read_after_status_status: None,
        pc_after_status_exit: None,
        pc_advance_after_status_status: None,
        continuation_run_status: None,
        continuation_exit_reason: None,
        continuation_exit_syndrome: None,
        continuation_exit_virtual_address: None,
        continuation_exit_physical_address: None,
        continuation_watchdog_cancel_status: None,
        status_value_after_continue_status: None,
        status_value_after_continue: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework MMIO serial device probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_mmio_rtc_device(
    allow_device: bool,
    host: HvfHostCapabilities,
) -> HvfMmioRtcDeviceProbe {
    HvfMmioRtcDeviceProbe {
        allowed: allow_device,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        rtc_address_register_set: false,
        device_bus_created: false,
        device_bus_device_count: 0,
        first_run_attempted: false,
        rtc_exit_observed: false,
        rtc_handled_by_device: false,
        rtc_value_injected: false,
        pc_read_after_rtc_exit: false,
        pc_advanced: false,
        second_run_attempted: false,
        continuation_exit_observed: false,
        rtc_value_preserved: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        device_models: BOOT_MMIO_DEVICE_MODELS,
        code_ipa_start: 0x4000_0000,
        uart_ipa: 0x5000_0000,
        rtc_ipa: 0x5000_1000,
        bytes: 16 * 1024,
        instructions: "LDR X0, [X1]; HVC #0",
        rtc_value: 0x2026_0618,
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        rtc_address_register_set_status: None,
        first_run_status: None,
        rtc_exit_reason: None,
        rtc_exit_syndrome: None,
        rtc_exit_virtual_address: None,
        rtc_exit_physical_address: None,
        first_watchdog_cancel_status: None,
        rtc_value_set_status: None,
        pc_read_status: None,
        pc_after_rtc_exit: None,
        pc_advance_status: None,
        second_run_status: None,
        continuation_exit_reason: None,
        continuation_exit_syndrome: None,
        continuation_exit_virtual_address: None,
        continuation_exit_physical_address: None,
        second_watchdog_cancel_status: None,
        rtc_value_after_continue_status: None,
        rtc_value_after_continue: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework MMIO RTC device probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_mmio_block_device(
    allow_device: bool,
    host: HvfHostCapabilities,
) -> HvfMmioBlockDeviceProbe {
    HvfMmioBlockDeviceProbe {
        allowed: allow_device,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        register_address_registers_set: false,
        device_bus_created: false,
        device_bus_device_count: 0,
        register_reads: unsupported_block_register_reads(),
        continuation_run_attempted: false,
        continuation_exit_observed: false,
        vendor_value_preserved: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        device_models: BOOT_MMIO_DEVICE_MODELS,
        code_ipa_start: 0x4000_0000,
        block_ipa: 0x5000_2000,
        bytes: 16 * 1024,
        instructions: "LDR W0 magic/version/device/vendor; HVC #0",
        magic_value: VIRTIO_MMIO_MAGIC_VALUE,
        version_value: VIRTIO_MMIO_VERSION_VALUE,
        device_id_value: VIRTIO_MMIO_BLOCK_DEVICE_ID_VALUE,
        vendor_id_value: VIRTIO_MMIO_VENDOR_ID_VALUE,
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        register_address_registers_set_status: vec![None; 4],
        continuation_run_status: None,
        continuation_exit_reason: None,
        continuation_exit_syndrome: None,
        continuation_exit_virtual_address: None,
        continuation_exit_physical_address: None,
        continuation_watchdog_cancel_status: None,
        vendor_value_after_continue_status: None,
        vendor_value_after_continue: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework MMIO block device probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

pub fn probe_hvf_mmio_block_queue(
    allow_device: bool,
    disk_path: Option<PathBuf>,
    iso_path: Option<PathBuf>,
    writable_disk_path: Option<PathBuf>,
    host: HvfHostCapabilities,
) -> HvfMmioBlockQueueProbe {
    let (block_backing_kind, block_backing_path) = if let Some(path) = writable_disk_path {
        ("host-file-writable", Some(path))
    } else if let Some(path) = iso_path {
        ("host-iso-readonly", Some(path))
    } else if let Some(path) = disk_path {
        ("host-file", Some(path))
    } else {
        ("synthetic-sector-pattern", None)
    };
    HvfMmioBlockQueueProbe {
        allowed: allow_device,
        attempted: false,
        vm_created: false,
        memory_allocated: false,
        memory_mapped: false,
        vcpu_created: false,
        pc_set: false,
        cpsr_set: false,
        device_bus_created: false,
        device_bus_device_count: 0,
        steps: unsupported_block_queue_steps(),
        continuation_run_attempted: false,
        continuation_exit_observed: false,
        capacity_high_value_preserved: false,
        watchdog_cancel_fired: false,
        vcpu_destroyed: false,
        memory_unmapped: false,
        vm_destroyed: false,
        memory_deallocated: false,
        host,
        device_models: BLOCK_QUEUE_MMIO_DEVICE_MODELS,
        code_ipa_start: 0x4000_0000,
        block_ipa: 0x5000_2000,
        bytes: 16 * 1024,
        instructions: "LDR/STR W0 VirtIO-MMIO queue/config/address/notify registers; HVC #0",
        device_features_value: VIRTIO_MMIO_BLOCK_DEVICE_FEATURES_VALUE,
        driver_features_value: VIRTIO_MMIO_BLOCK_DRIVER_FEATURES_VALUE,
        queue_select_value: VIRTIO_MMIO_BLOCK_QUEUE_SEL_VALUE,
        queue_num_max_value: VIRTIO_MMIO_BLOCK_QUEUE_NUM_MAX_VALUE,
        queue_num_value: VIRTIO_MMIO_BLOCK_QUEUE_NUM_VALUE,
        queue_ready_value: VIRTIO_MMIO_BLOCK_QUEUE_READY_VALUE,
        queue_desc_address: VIRTIO_MMIO_BLOCK_QUEUE_DESC_ADDRESS,
        queue_driver_address: VIRTIO_MMIO_BLOCK_QUEUE_DRIVER_ADDRESS,
        queue_device_address: VIRTIO_MMIO_BLOCK_QUEUE_DEVICE_ADDRESS,
        queue_notify_value: VIRTIO_MMIO_BLOCK_QUEUE_NOTIFY_VALUE,
        interrupt_status_value: VIRTIO_MMIO_INTERRUPT_USED_BUFFER_VALUE,
        block_backing_kind,
        block_backing_path,
        request_ring_seeded: false,
        request_completed_after_notify: false,
        request_descriptor_index: None,
        request_sector: None,
        request_byte_offset: None,
        request_data_bytes: None,
        request_data_prefix: Vec::new(),
        request_status: None,
        request_used_index: None,
        request_used_len: None,
        request_interrupt_status: None,
        write_completed_after_notify: false,
        write_request_type: None,
        write_sector: None,
        write_byte_offset: None,
        write_data_bytes: None,
        write_data_prefix: Vec::new(),
        write_status: None,
        write_used_index: None,
        write_used_len: None,
        flush_completed_after_notify: false,
        flush_request_type: None,
        flush_status: None,
        flush_used_index: None,
        flush_used_len: None,
        persisted_data_prefix: Vec::new(),
        status_value: VIRTIO_MMIO_BLOCK_STATUS_VALUE,
        capacity_sectors: VIRTIO_MMIO_BLOCK_CAPACITY_SECTORS,
        vm_create_status: None,
        allocate_status: None,
        map_status: None,
        vcpu_create_status: None,
        pc_set_status: None,
        cpsr_set_status: None,
        continuation_run_status: None,
        continuation_exit_reason: None,
        continuation_exit_syndrome: None,
        continuation_exit_virtual_address: None,
        continuation_exit_physical_address: None,
        continuation_watchdog_cancel_status: None,
        capacity_high_after_continue_status: None,
        capacity_high_after_continue: None,
        vcpu_destroy_status: None,
        unmap_status: None,
        vm_destroy_status: None,
        deallocate_status: None,
        blockers: vec![
            "Apple Hypervisor.framework MMIO block queue/config/address/notify probe is only available on Apple Silicon macOS".to_string(),
        ],
    }
}

fn unsupported_block_register_reads() -> Vec<HvfMmioBlockRegisterProbe> {
    [
        ("magic", 0x5000_2000, VIRTIO_MMIO_MAGIC_VALUE),
        ("version", 0x5000_2004, VIRTIO_MMIO_VERSION_VALUE),
        ("device_id", 0x5000_2008, VIRTIO_MMIO_BLOCK_DEVICE_ID_VALUE),
        ("vendor_id", 0x5000_200c, VIRTIO_MMIO_VENDOR_ID_VALUE),
    ]
    .into_iter()
    .map(|(name, ipa, expected_value)| HvfMmioBlockRegisterProbe {
        name,
        ipa,
        expected_value,
        run_attempted: false,
        exit_observed: false,
        handled_by_device: false,
        value_injected: false,
        pc_read_after_exit: false,
        pc_advanced: false,
        run_status: None,
        exit_reason: None,
        exit_syndrome: None,
        exit_virtual_address: None,
        exit_physical_address: None,
        watchdog_cancel_status: None,
        value_set_status: None,
        pc_read_status: None,
        pc_after_exit: None,
        pc_advance_status: None,
    })
    .collect()
}

fn unsupported_block_queue_steps() -> Vec<HvfMmioBlockQueueStepProbe> {
    [
        (
            "device_features",
            "read",
            0x5000_2010,
            Some(VIRTIO_MMIO_BLOCK_DEVICE_FEATURES_VALUE),
            None,
        ),
        (
            "driver_features",
            "write",
            0x5000_2020,
            None,
            Some(VIRTIO_MMIO_BLOCK_DRIVER_FEATURES_VALUE),
        ),
        (
            "status_ack",
            "write",
            0x5000_2070,
            None,
            Some(VIRTIO_MMIO_BLOCK_STATUS_ACK_VALUE),
        ),
        (
            "status_driver",
            "write",
            0x5000_2070,
            None,
            Some(VIRTIO_MMIO_BLOCK_STATUS_DRIVER_VALUE),
        ),
        (
            "status_features_ok",
            "write",
            0x5000_2070,
            None,
            Some(VIRTIO_MMIO_BLOCK_STATUS_FEATURES_OK_VALUE),
        ),
        (
            "queue_select",
            "write",
            0x5000_2030,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_SEL_VALUE),
        ),
        (
            "queue_num_max",
            "read",
            0x5000_2034,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_NUM_MAX_VALUE),
            None,
        ),
        (
            "queue_num",
            "write",
            0x5000_2038,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_NUM_VALUE),
        ),
        (
            "queue_desc_low",
            "write",
            0x5000_2080,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DESC_ADDRESS & 0xffff_ffff),
        ),
        (
            "queue_desc_high",
            "write",
            0x5000_2084,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DESC_ADDRESS >> 32),
        ),
        (
            "queue_driver_low",
            "write",
            0x5000_2090,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DRIVER_ADDRESS & 0xffff_ffff),
        ),
        (
            "queue_driver_high",
            "write",
            0x5000_2094,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DRIVER_ADDRESS >> 32),
        ),
        (
            "queue_device_low",
            "write",
            0x5000_20a0,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DEVICE_ADDRESS & 0xffff_ffff),
        ),
        (
            "queue_device_high",
            "write",
            0x5000_20a4,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DEVICE_ADDRESS >> 32),
        ),
        (
            "queue_ready",
            "write",
            0x5000_2044,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_READY_VALUE),
        ),
        (
            "status_driver_ok",
            "write",
            0x5000_2070,
            None,
            Some(VIRTIO_MMIO_BLOCK_STATUS_VALUE),
        ),
        (
            "status",
            "read",
            0x5000_2070,
            Some(VIRTIO_MMIO_BLOCK_STATUS_VALUE),
            None,
        ),
        (
            "queue_notify",
            "write",
            0x5000_2050,
            None,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_NOTIFY_VALUE),
        ),
        (
            "queue_ready",
            "read",
            0x5000_2044,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_READY_VALUE),
            None,
        ),
        (
            "queue_desc_low",
            "read",
            0x5000_2080,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DESC_ADDRESS & 0xffff_ffff),
            None,
        ),
        (
            "queue_driver_low",
            "read",
            0x5000_2090,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DRIVER_ADDRESS & 0xffff_ffff),
            None,
        ),
        (
            "queue_device_low",
            "read",
            0x5000_20a0,
            Some(VIRTIO_MMIO_BLOCK_QUEUE_DEVICE_ADDRESS & 0xffff_ffff),
            None,
        ),
        (
            "interrupt_status",
            "read",
            0x5000_2060,
            Some(VIRTIO_MMIO_INTERRUPT_USED_BUFFER_VALUE),
            None,
        ),
        ("config_generation", "read", 0x5000_20fc, Some(0), None),
        (
            "capacity_low",
            "read",
            0x5000_2100,
            Some(VIRTIO_MMIO_BLOCK_CAPACITY_SECTORS & 0xffff_ffff),
            None,
        ),
        (
            "capacity_high",
            "read",
            0x5000_2104,
            Some(VIRTIO_MMIO_BLOCK_CAPACITY_SECTORS >> 32),
            None,
        ),
    ]
    .into_iter()
    .map(
        |(name, access, ipa, expected_value, write_value)| HvfMmioBlockQueueStepProbe {
            name,
            access,
            ipa,
            expected_value,
            write_value,
            run_attempted: false,
            address_register_set: false,
            write_value_register_set: false,
            exit_observed: false,
            handled_by_device: false,
            value_injected: false,
            write_accepted: false,
            pc_read_after_exit: false,
            pc_advanced: false,
            captured_write_value: None,
            run_status: None,
            address_register_set_status: None,
            write_value_register_set_status: None,
            exit_reason: None,
            exit_syndrome: None,
            exit_virtual_address: None,
            exit_physical_address: None,
            watchdog_cancel_status: None,
            value_set_status: None,
            pc_read_status: None,
            pc_after_exit: None,
            pc_advance_status: None,
        },
    )
    .collect()
}
