//! Split out of mmio_block.rs by responsibility.

use super::super::*;
use super::*;
use crate::*;

pub(crate) fn block_queue_step_specs() -> [BlockQueueStepSpec; 26] {
    [
        BlockQueueStepSpec {
            name: "device_features",
            access: BlockQueueAccessKind::Read,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_DEVICE_FEATURES_OFFSET,
            expected_value: Some(VIRTIO_MMIO_BLOCK_DEVICE_FEATURES_VALUE),
            write_value: None,
            instruction: AARCH64_LDR_W0_FROM_X1,
        },
        BlockQueueStepSpec {
            name: "driver_features",
            access: BlockQueueAccessKind::Write,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_DRIVER_FEATURES_OFFSET,
            expected_value: None,
            write_value: Some(VIRTIO_MMIO_BLOCK_DRIVER_FEATURES_VALUE),
            instruction: AARCH64_STR_W0_TO_X1,
        },
        BlockQueueStepSpec {
            name: "status_ack",
            access: BlockQueueAccessKind::Write,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_STATUS_OFFSET,
            expected_value: None,
            write_value: Some(VIRTIO_MMIO_BLOCK_STATUS_ACK_VALUE),
            instruction: AARCH64_STR_W0_TO_X1,
        },
        BlockQueueStepSpec {
            name: "status_driver",
            access: BlockQueueAccessKind::Write,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_STATUS_OFFSET,
            expected_value: None,
            write_value: Some(VIRTIO_MMIO_BLOCK_STATUS_DRIVER_VALUE),
            instruction: AARCH64_STR_W0_TO_X1,
        },
        BlockQueueStepSpec {
            name: "status_features_ok",
            access: BlockQueueAccessKind::Write,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_STATUS_OFFSET,
            expected_value: None,
            write_value: Some(VIRTIO_MMIO_BLOCK_STATUS_FEATURES_OK_VALUE),
            instruction: AARCH64_STR_W0_TO_X1,
        },
        BlockQueueStepSpec {
            name: "queue_select",
            access: BlockQueueAccessKind::Write,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_QUEUE_SEL_OFFSET,
            expected_value: None,
            write_value: Some(VIRTIO_MMIO_BLOCK_QUEUE_SEL_VALUE),
            instruction: AARCH64_STR_W0_TO_X1,
        },
        BlockQueueStepSpec {
            name: "queue_num_max",
            access: BlockQueueAccessKind::Read,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_QUEUE_NUM_MAX_OFFSET,
            expected_value: Some(VIRTIO_MMIO_BLOCK_QUEUE_NUM_MAX_VALUE),
            write_value: None,
            instruction: AARCH64_LDR_W0_FROM_X1,
        },
        BlockQueueStepSpec {
            name: "queue_num",
            access: BlockQueueAccessKind::Write,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_QUEUE_NUM_OFFSET,
            expected_value: None,
            write_value: Some(VIRTIO_MMIO_BLOCK_QUEUE_NUM_VALUE),
            instruction: AARCH64_STR_W0_TO_X1,
        },
        BlockQueueStepSpec {
            name: "queue_desc_low",
            access: BlockQueueAccessKind::Write,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_QUEUE_DESC_LOW_OFFSET,
            expected_value: None,
            write_value: Some(VIRTIO_MMIO_BLOCK_QUEUE_DESC_ADDRESS & 0xffff_ffff),
            instruction: AARCH64_STR_W0_TO_X1,
        },
        BlockQueueStepSpec {
            name: "queue_desc_high",
            access: BlockQueueAccessKind::Write,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_QUEUE_DESC_HIGH_OFFSET,
            expected_value: None,
            write_value: Some(VIRTIO_MMIO_BLOCK_QUEUE_DESC_ADDRESS >> 32),
            instruction: AARCH64_STR_W0_TO_X1,
        },
        BlockQueueStepSpec {
            name: "queue_driver_low",
            access: BlockQueueAccessKind::Write,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_QUEUE_DRIVER_LOW_OFFSET,
            expected_value: None,
            write_value: Some(VIRTIO_MMIO_BLOCK_QUEUE_DRIVER_ADDRESS & 0xffff_ffff),
            instruction: AARCH64_STR_W0_TO_X1,
        },
        BlockQueueStepSpec {
            name: "queue_driver_high",
            access: BlockQueueAccessKind::Write,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_QUEUE_DRIVER_HIGH_OFFSET,
            expected_value: None,
            write_value: Some(VIRTIO_MMIO_BLOCK_QUEUE_DRIVER_ADDRESS >> 32),
            instruction: AARCH64_STR_W0_TO_X1,
        },
        BlockQueueStepSpec {
            name: "queue_device_low",
            access: BlockQueueAccessKind::Write,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_QUEUE_DEVICE_LOW_OFFSET,
            expected_value: None,
            write_value: Some(VIRTIO_MMIO_BLOCK_QUEUE_DEVICE_ADDRESS & 0xffff_ffff),
            instruction: AARCH64_STR_W0_TO_X1,
        },
        BlockQueueStepSpec {
            name: "queue_device_high",
            access: BlockQueueAccessKind::Write,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_QUEUE_DEVICE_HIGH_OFFSET,
            expected_value: None,
            write_value: Some(VIRTIO_MMIO_BLOCK_QUEUE_DEVICE_ADDRESS >> 32),
            instruction: AARCH64_STR_W0_TO_X1,
        },
        BlockQueueStepSpec {
            name: "queue_ready",
            access: BlockQueueAccessKind::Write,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_QUEUE_READY_OFFSET,
            expected_value: None,
            write_value: Some(VIRTIO_MMIO_BLOCK_QUEUE_READY_VALUE),
            instruction: AARCH64_STR_W0_TO_X1,
        },
        BlockQueueStepSpec {
            name: "status_driver_ok",
            access: BlockQueueAccessKind::Write,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_STATUS_OFFSET,
            expected_value: None,
            write_value: Some(VIRTIO_MMIO_BLOCK_STATUS_VALUE),
            instruction: AARCH64_STR_W0_TO_X1,
        },
        BlockQueueStepSpec {
            name: "status",
            access: BlockQueueAccessKind::Read,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_STATUS_OFFSET,
            expected_value: Some(VIRTIO_MMIO_BLOCK_STATUS_VALUE),
            write_value: None,
            instruction: AARCH64_LDR_W0_FROM_X1,
        },
        BlockQueueStepSpec {
            name: "queue_notify",
            access: BlockQueueAccessKind::Write,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_QUEUE_NOTIFY_OFFSET,
            expected_value: None,
            write_value: Some(VIRTIO_MMIO_BLOCK_QUEUE_NOTIFY_VALUE),
            instruction: AARCH64_STR_W0_TO_X1,
        },
        BlockQueueStepSpec {
            name: "queue_ready",
            access: BlockQueueAccessKind::Read,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_QUEUE_READY_OFFSET,
            expected_value: Some(VIRTIO_MMIO_BLOCK_QUEUE_READY_VALUE),
            write_value: None,
            instruction: AARCH64_LDR_W0_FROM_X1,
        },
        BlockQueueStepSpec {
            name: "queue_desc_low",
            access: BlockQueueAccessKind::Read,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_QUEUE_DESC_LOW_OFFSET,
            expected_value: Some(VIRTIO_MMIO_BLOCK_QUEUE_DESC_ADDRESS & 0xffff_ffff),
            write_value: None,
            instruction: AARCH64_LDR_W0_FROM_X1,
        },
        BlockQueueStepSpec {
            name: "queue_driver_low",
            access: BlockQueueAccessKind::Read,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_QUEUE_DRIVER_LOW_OFFSET,
            expected_value: Some(VIRTIO_MMIO_BLOCK_QUEUE_DRIVER_ADDRESS & 0xffff_ffff),
            write_value: None,
            instruction: AARCH64_LDR_W0_FROM_X1,
        },
        BlockQueueStepSpec {
            name: "queue_device_low",
            access: BlockQueueAccessKind::Read,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_QUEUE_DEVICE_LOW_OFFSET,
            expected_value: Some(VIRTIO_MMIO_BLOCK_QUEUE_DEVICE_ADDRESS & 0xffff_ffff),
            write_value: None,
            instruction: AARCH64_LDR_W0_FROM_X1,
        },
        BlockQueueStepSpec {
            name: "interrupt_status",
            access: BlockQueueAccessKind::Read,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_INTERRUPT_STATUS_OFFSET,
            expected_value: Some(VIRTIO_MMIO_INTERRUPT_USED_BUFFER_VALUE),
            write_value: None,
            instruction: AARCH64_LDR_W0_FROM_X1,
        },
        BlockQueueStepSpec {
            name: "config_generation",
            access: BlockQueueAccessKind::Read,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_CONFIG_GENERATION_OFFSET,
            expected_value: Some(VIRTIO_MMIO_BLOCK_CONFIG_GENERATION_VALUE),
            write_value: None,
            instruction: AARCH64_LDR_W0_FROM_X1,
        },
        BlockQueueStepSpec {
            name: "capacity_low",
            access: BlockQueueAccessKind::Read,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_BLOCK_CAPACITY_LOW_OFFSET,
            expected_value: Some(VIRTIO_MMIO_BLOCK_CAPACITY_SECTORS & 0xffff_ffff),
            write_value: None,
            instruction: AARCH64_LDR_W0_FROM_X1,
        },
        BlockQueueStepSpec {
            name: "capacity_high",
            access: BlockQueueAccessKind::Read,
            ipa: BLOCK_MMIO_IPA + VIRTIO_MMIO_BLOCK_CAPACITY_HIGH_OFFSET,
            expected_value: Some(VIRTIO_MMIO_BLOCK_CAPACITY_SECTORS >> 32),
            write_value: None,
            instruction: AARCH64_LDR_W0_FROM_X1,
        },
    ]
}

pub(crate) fn block_queue_step_defaults() -> Vec<HvfMmioBlockQueueStepProbe> {
    block_queue_step_specs()
        .iter()
        .map(|spec| HvfMmioBlockQueueStepProbe {
            name: spec.name,
            access: spec.access.as_str(),
            ipa: spec.ipa,
            expected_value: spec.expected_value,
            write_value: spec.write_value,
            run_attempted: false,
            address_register_set: false,
            write_value_register_set: false,
            exit_observed: false,
            handled_by_device: false,
            value_injected: false,
            write_accepted: false,
            pc_read_after_exit: false,
            pc_advanced: false,
            captured_write_value: None,
            run_status: None,
            address_register_set_status: None,
            write_value_register_set_status: None,
            exit_reason: None,
            exit_syndrome: None,
            exit_virtual_address: None,
            exit_physical_address: None,
            watchdog_cancel_status: None,
            value_set_status: None,
            pc_read_status: None,
            pc_after_exit: None,
            pc_advance_status: None,
        })
        .collect()
}
