#!/usr/bin/env bash
# Check host and driver-package readiness before a Windows P3 viogpu3d boot.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VIOGPU3D_DIR="${VIOGPU3D_DIR:-}"
VIOGPU3D_MANIFEST="${VIOGPU3D_MANIFEST:-}"
VIOGPU3D_PCI_DEVICE_ID="${VIOGPU3D_PCI_DEVICE_ID:-10f7}"
REQUIRE_DRIVER_PACKAGE="${REQUIRE_DRIVER_PACKAGE:-0}"
PROBE_HOST_RENDERER="${PROBE_HOST_RENDERER:-0}"
VENUS_HOST_RENDERER_PROBE="${VENUS_HOST_RENDERER_PROBE:-"$ROOT/scripts/run-venus-host-probe.sh"}"
VIRGL_HOST_RENDERER_PROBE="${VIRGL_HOST_RENDERER_PROBE:-"$ROOT/scripts/run-virgl-host-probe.sh"}"
HOST_PROTOCOL="${BRIDGEVM_VIRTIO_GPU_3D_PROTOCOL:-venus}"

usage() {
  cat >&2 <<'EOF'
usage: scripts/check-hvf-windows-p3-gpu-readiness.sh [--driver-dir DIR] [--manifest PATH] [--pci-device-id 1050|10f7] [--require-driver-package] [--probe-host-renderer]

Environment:
  VIOGPU3D_DIR       Optional viogpu3d package directory. May also be passed
                     with --driver-dir.
  VIOGPU3D_PROTOCOL  auto, venus, or virgl. Forwarded to the package checker.
  VIOGPU3D_MANIFEST  Optional path for the package manifest generated by the
                     package checker. May also be passed with --manifest.
  VIOGPU3D_PCI_DEVICE_ID
                     Expected virtio-gpu PCI device id for the boot, 1050 or
                     10f7. Default: 10f7, matching --virtio-gpu-3d's current
                     explicit bind-id alias unless the boot wrapper overrides it.
  REQUIRE_DRIVER_PACKAGE
                     Set to 1 to fail when no package is provided. The
                     --require-driver-package flag is equivalent.
  PROBE_HOST_RENDERER
                     Set to 1, or pass --probe-host-renderer, to run the live
                     host renderer probe for the package protocol.
  VENUS_HOST_RENDERER_PROBE
                     Probe command for protocol=venus. Default:
                     scripts/run-venus-host-probe.sh.
  VIRGL_HOST_RENDERER_PROBE
                     Probe command for protocol=virgl. Default:
                     scripts/run-virgl-host-probe.sh.
  BRIDGEVM_VIRTIO_GPU_3D_PROTOCOL
                     Host runtime backend protocol, venus or virgl. Default:
                     venus.

This is a no-VM preflight: it runs the synthetic host 3D preflight and, when a
driver package is provided, checks that the package protocol is compatible with
the selected HVF 3D runtime. Unlike the injection inventory, this render gate
also requires a VirGL package with ARM64 user-mode DLLs, active WDDM/OpenGL INF
registrations, and CopyFiles mappings that place the registered DLLs in DirID
11. A KMD-only Venus package remains injection-ready but is not classified as a
render candidate. The live host renderer probe is optional because it builds
and runs host renderer tooling.
EOF
}

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

normalize_pci_device_id() {
  local value="$1"
  local upper
  upper="$(printf '%s\n' "$value" | tr '[:lower:]' '[:upper:]')"
  upper="${upper#0X}"
  case "$upper" in
    1050|10F7) printf '%s\n' "$upper" ;;
    *) fail "VIOGPU3D_PCI_DEVICE_ID must be 1050 or 10f7, got: $value" ;;
  esac
}

protocol_display_name() {
  case "$1" in
    venus) printf 'VENUS\n' ;;
    virgl) printf 'VIRGL\n' ;;
    *) fail "unsupported virtio-gpu 3D protocol: $1" ;;
  esac
}

protocol_capset_id() {
  case "$1" in
    venus) printf '4\n' ;;
    virgl) printf '1\n' ;;
    *) fail "unsupported virtio-gpu 3D protocol: $1" ;;
  esac
}

kv_value() {
  local key="$1"
  awk -v key="$key" 'index($0, key "=") == 1 { sub(/^[^=]*=/, ""); print; exit }'
}

host_renderer_probe_command() {
  case "$1" in
    venus) printf '%s\n' "$VENUS_HOST_RENDERER_PROBE" ;;
    virgl) printf '%s\n' "$VIRGL_HOST_RENDERER_PROBE" ;;
    *) fail "unsupported virtio-gpu 3D protocol: $1" ;;
  esac
}

probe_host_renderer() {
  local protocol="$1"
  local key="host_renderer_$protocol"
  local command
  local output
  local status
  local renderer_available
  local renderer_state
  local unavailable_reason
  local init_line
  local renderer_cookie_nonnull
  local gl_context_callbacks

  command="$(host_renderer_probe_command "$protocol")"
  printf '%s_probe=REQUESTED\n' "$key"
  printf '%s_probe_command=%s\n' "$key" "$command"

  if [[ ! -x "$command" ]]; then
    printf '%s_probe_exit_status=127\n' "$key"
    printf '%s=NOT_AVAILABLE\n' "$key"
    printf '%s_available=false\n' "$key"
    printf '%s_unavailable_reason=probe command is not executable: %s\n' "$key" "$command"
    return 1
  fi

  set +e
  output="$("$command" 2>&1)"
  status="$?"
  set -e

  renderer_available="$(printf '%s\n' "$output" | kv_value renderer_available)"
  renderer_state="$(printf '%s\n' "$output" | kv_value "$key")"
  unavailable_reason="$(printf '%s\n' "$output" | kv_value unavailable_reason)"
  renderer_cookie_nonnull="$(printf '%s\n' "$output" | kv_value renderer_cookie_nonnull)"
  gl_context_callbacks="$(printf '%s\n' "$output" | kv_value gl_context_callbacks)"
  init_line="$(printf '%s\n' "$output" | awk '/virgl_renderer_init / { print; exit }')"

  if [[ -z "$renderer_state" ]]; then
    if [[ "$renderer_available" == "true" ]]; then
      renderer_state="AVAILABLE"
    elif [[ "$renderer_available" == "false" ]]; then
      renderer_state="NOT_AVAILABLE"
    else
      renderer_state="UNKNOWN"
    fi
  fi
  if [[ -z "$renderer_available" ]]; then
    case "$renderer_state" in
      AVAILABLE) renderer_available="true" ;;
      NOT_AVAILABLE) renderer_available="false" ;;
      *) renderer_available="unknown" ;;
    esac
  fi
  if [[ -z "$unavailable_reason" && "$renderer_state" != "AVAILABLE" ]]; then
    unavailable_reason="probe command failed or did not report availability"
  fi

  printf '%s_probe_exit_status=%s\n' "$key" "$status"
  [[ -z "$renderer_cookie_nonnull" ]] || printf '%s_cookie_nonnull=%s\n' "$key" "$renderer_cookie_nonnull"
  [[ -z "$gl_context_callbacks" ]] || printf '%s_gl_context_callbacks=%s\n' "$key" "$gl_context_callbacks"
  [[ -z "$init_line" ]] || printf '%s_init=%s\n' "$key" "$init_line"
  printf '%s=%s\n' "$key" "$renderer_state"
  printf '%s_available=%s\n' "$key" "$renderer_available"
  [[ -z "$unavailable_reason" ]] || printf '%s_unavailable_reason=%s\n' "$key" "$unavailable_reason"

  [[ "$status" == "0" && "$renderer_state" == "AVAILABLE" && "$renderer_available" == "true" ]]
}

check_protocol_preflight() {
  local protocol="$1"
  local prefix="$2"
  local output
  local display_name
  local capset_id

  display_name="$(protocol_display_name "$protocol")"
  capset_id="$(protocol_capset_id "$protocol")"
  printf '%s_preflight_command=bridgevm hvf virtio-gpu-3d-host-preflight --protocol %s\n' \
    "$prefix" "$protocol"

  output="$(cargo run -q -p bridgevm-cli -- hvf virtio-gpu-3d-host-preflight --protocol "$protocol" 2>&1)" || {
    printf '%s\n' "$output"
    fail "$prefix virtio-gpu 3D preflight command failed"
  }
  case "$output" in
    *"$display_name expected capset id $capset_id: true"* ) ;;
    *)
      printf '%s\n' "$output"
      fail "$prefix preflight did not prove $display_name capset id $capset_id"
      ;;
  esac
  case "$output" in
    *"Blockers: none"* ) ;;
    *)
      printf '%s\n' "$output"
      fail "$prefix preflight reported blockers"
      ;;
  esac
  printf '%s_preflight=PASS\n' "$prefix"
  printf '%s_expected_capset_id=%s\n' "$prefix" "$capset_id"
  printf '%s_expected_capset_ok=true\n' "$prefix"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --driver-dir)
      [[ $# -ge 2 ]] || { usage; exit 2; }
      VIOGPU3D_DIR="$2"
      shift 2
      ;;
    --require-driver-package)
      REQUIRE_DRIVER_PACKAGE="1"
      shift
      ;;
    --probe-host-renderer)
      PROBE_HOST_RENDERER="1"
      shift
      ;;
    --manifest)
      [[ $# -ge 2 ]] || { usage; exit 2; }
      VIOGPU3D_MANIFEST="$2"
      shift 2
      ;;
    --pci-device-id)
      [[ $# -ge 2 ]] || { usage; exit 2; }
      VIOGPU3D_PCI_DEVICE_ID="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 2
      ;;
  esac
done

case "$REQUIRE_DRIVER_PACKAGE" in
  0|1) ;;
  *) fail "REQUIRE_DRIVER_PACKAGE must be 0 or 1" ;;
esac
case "$PROBE_HOST_RENDERER" in
  0|1) ;;
  *) fail "PROBE_HOST_RENDERER must be 0 or 1" ;;
esac
case "$HOST_PROTOCOL" in
  venus|virgl) ;;
  *) fail "BRIDGEVM_VIRTIO_GPU_3D_PROTOCOL must be venus or virgl" ;;
esac
VIOGPU3D_PCI_DEVICE_ID="$(normalize_pci_device_id "$VIOGPU3D_PCI_DEVICE_ID")"

printf 'BridgeVM P3 Windows GPU readiness\n'
printf 'host_protocol=%s\n' "$HOST_PROTOCOL"
printf 'expected_hwid=PCI\\VEN_1AF4&DEV_%s\n' "$VIOGPU3D_PCI_DEVICE_ID"
check_protocol_preflight "$HOST_PROTOCOL" "host"

if [[ -z "$VIOGPU3D_DIR" ]]; then
  printf 'driver_package=missing\n'
  printf 'end_to_end_windows_3d=NOT_PASSED\n'
  printf 'boot_ready=false\n'
  if [[ "$REQUIRE_DRIVER_PACKAGE" == "1" ]]; then
    fail "missing viogpu3d package; pass --driver-dir or set VIOGPU3D_DIR"
  fi
  printf 'Blocker: missing viogpu3d package for injection\n'
  exit 0
fi

package_output="$(
  checker_args=("$ROOT/scripts/check-hvf-windows-viogpu3d-package.sh")
  if [[ -n "$VIOGPU3D_MANIFEST" ]]; then
    checker_args+=(--manifest "$VIOGPU3D_MANIFEST")
  fi
  checker_args+=(--pci-device-id "$VIOGPU3D_PCI_DEVICE_ID")
  checker_args+=(--require-render-candidate)
  checker_args+=("$VIOGPU3D_DIR")
  VIOGPU3D_PROTOCOL="${VIOGPU3D_PROTOCOL:-auto}" "${checker_args[@]}" 2>&1
)" || {
  printf '%s\n' "$package_output"
  printf 'end_to_end_windows_3d=NOT_PASSED\n'
  printf 'boot_ready=false\n'
  fail "viogpu3d package check failed"
}
printf '%s\n' "$package_output"
package_protocol="$(awk -F= '$1 == "protocol" { print $2; exit }' <<<"$package_output")"
[[ -n "$package_protocol" ]] || fail "package checker did not report protocol"
package_render_candidate="$(awk -F= '$1 == "render_candidate" { print $2; exit }' <<<"$package_output")"
[[ "$package_render_candidate" == "true" ]] || fail "package checker did not prove a render candidate"

printf 'driver_package=present\n'
printf 'driver_protocol=%s\n' "$package_protocol"
printf 'driver_render_candidate=%s\n' "$package_render_candidate"
printf 'recommended_gpu_trace_protocol=%s\n' "$package_protocol"
if [[ "$package_protocol" == "$HOST_PROTOCOL" ]]; then
  printf 'package_protocol_device_model_preflight=PASS\n'
  printf 'package_protocol_device_model_expected_capset_id=%s\n' "$(protocol_capset_id "$package_protocol")"
  printf 'package_protocol_device_model_expected_capset_ok=true\n'
else
  check_protocol_preflight "$package_protocol" "package_protocol_device_model"
fi

if [[ "$package_protocol" != "$HOST_PROTOCOL" ]]; then
  printf 'host_backend_protocol=%s\n' "$HOST_PROTOCOL"
  printf 'host_backend_%s_runtime=NOT_WIRED\n' "$package_protocol"
  renderer_ok=0
  if [[ "$PROBE_HOST_RENDERER" == "1" ]]; then
    probe_host_renderer "$package_protocol" && renderer_ok=1 || renderer_ok=0
  else
    printf 'host_renderer_%s=NOT_PROBED\n' "$package_protocol"
  fi
  printf 'end_to_end_windows_3d=NOT_PASSED\n'
  printf 'boot_ready=false\n'
  if [[ "$PROBE_HOST_RENDERER" == "1" && "$renderer_ok" != "1" ]]; then
    fail "package protocol=$package_protocol has synthetic device-model preflight PASS but real host renderer is not available; current host backend protocol=$HOST_PROTOCOL"
  fi
  if [[ "$PROBE_HOST_RENDERER" == "1" && "$renderer_ok" == "1" ]]; then
    fail "package protocol=$package_protocol has synthetic device-model preflight PASS and a live host renderer, but the HVF boot backend is still protocol=$HOST_PROTOCOL; do not boot until the matching runtime backend is wired"
  fi
  fail "package protocol=$package_protocol has synthetic device-model preflight PASS but current host backend protocol=$HOST_PROTOCOL; do not boot until a matching runtime backend is wired"
fi

printf 'host_backend_protocol=%s\n' "$HOST_PROTOCOL"
printf 'host_backend_%s_runtime=WIRED\n' "$HOST_PROTOCOL"
if [[ "$PROBE_HOST_RENDERER" == "1" ]]; then
  probe_host_renderer "$package_protocol" || {
    printf 'end_to_end_windows_3d=NOT_PASSED\n'
    printf 'boot_ready=false\n'
    fail "package protocol=$package_protocol matches host protocol but real host renderer is not available"
  }
fi
printf 'end_to_end_windows_3d=NOT_PASSED\n'
printf 'boot_ready=true\n'
printf 'recommended_boot_flags=--virtio-gpu-3d --gpu-trace PATH --gpu-trace-protocol %s --require-gpu-trace-gate\n' "$package_protocol"
printf 'PASS: P3 Windows GPU readiness\n'
