#!/usr/bin/env python3
"""Generate a runner manifest for the XCTest shim.

Apple's XCTest discovers `test*` methods through the Objective-C runtime. The
shim's XCTestCase is a plain Swift class, so those methods are not selectors
and cannot be found that way. This walks the test sources and writes an
explicit list instead.

Explicit is the right trade here: if a test stops being listed, the count
changes and the drift check fails. A discovery mechanism that silently finds
nothing would report success over an empty run.
"""
import re
import sys
from pathlib import Path

CLASS_RE = re.compile(r'^(?:final\s+)?class\s+(\w+)\s*:\s*XCTestCase\b', re.M)
# `throws` matters: the call site needs `try`, and a thrown XCTSkip is a skip.
FUNC_RE = re.compile(r'^\s*func\s+(test\w*)\s*\(\s*\)\s*(async\s+)?(throws)?', re.M)


def suites(root: Path):
    for path in sorted(root.rglob("*.swift")):
        text = path.read_text()
        module = path.relative_to(root).parts[0]
        # Split on class boundaries so methods attach to the right class.
        marks = [(m.start(), m.group(1)) for m in CLASS_RE.finditer(text)]
        for i, (start, name) in enumerate(marks):
            end = marks[i + 1][0] if i + 1 < len(marks) else len(text)
            methods = [(m.group(1), bool(m.group(2)), bool(m.group(3)))
                       for m in FUNC_RE.finditer(text[start:end])]
            if methods:
                yield module, name, methods


def main() -> int:
    root = Path(sys.argv[1])
    out = Path(sys.argv[2])
    lines = ["// Generated by scripts/generate-xctest-manifest.py. Do not edit.",
             "//", "// One entry per test method, because the shim cannot discover them.",
             "import Foundation", "import XCTest", "",
             "/// Runs an async test body to completion on the calling thread.",
             "func runBlocking<T>(_ body: @escaping () async throws -> T) throws -> T {",
             "    let semaphore = DispatchSemaphore(value: 0)",
             "    var result: Result<T, Error>!",
             "    Task {",
             "        do { result = .success(try await body()) }",
             "        catch { result = .failure(error) }",
             "        semaphore.signal()",
             "    }",
             "    semaphore.wait()",
             "    return try result.get()",
             "}", ""]
    # No imports of the test modules: their sources compile into this target,
    # because a SwiftPM test target builds a bundle an executable cannot link.
    # @MainActor: many suites are main-actor isolated (SwiftUI models), and
    # calling them from a nonisolated context is a compile error. Apple's
    # XCTest runs those on the main thread too.
    lines += ["", "@MainActor", "func xctestSuiteEntries() -> [XCTestSuiteEntry] { [" ]
    total = 0
    for module, cls, methods in suites(root):
        for name, is_async, throws in methods:
            total += 1
            # 201 of these are async. Skipping them would have quietly dropped
            # a third of the suite while still printing a pass.
            inner = f"try await instance.{name}()" if throws else f"await instance.{name}()"
            # runBlocking always throws (it rethrows the body's error), so the
            # call site needs try even when the test body does not throw.
            call = (f"try runBlocking {{ {inner} }}" if is_async
                    else (f"try instance.{name}()" if throws else f"instance.{name}()"))
            body = (f'    XCTestSuiteEntry(name: "{cls}.{name}") {{\n'
                    f'        _ = XCTestRecorder.shared.drain()\n'
                    f'        let instance = {cls}()\n'
                    f'        do {{\n'
                    f'            try instance.setUpWithError()\n'
                    f'            instance.setUp()\n'
                    f'            {call}\n'
                    f'            instance.tearDown()\n'
                    f'            try instance.tearDownWithError()\n'
                    f'        }} catch let skip as XCTSkipError {{\n'
                    f'            instance.runTeardownBlocks()\n'
                    f'            _ = XCTestRecorder.shared.drain()\n'
                    f'            return ["SKIPPED: \\(skip.message)"]\n'
                    f'        }} catch {{\n'
                    f'            XCTestRecorder.shared.record("threw \\(error)")\n'
                    f'        }}\n'
                    f'        instance.runTeardownBlocks()\n'
                    f'        return XCTestRecorder.shared.drain()\n'
                    f'    }},')
            lines.append(body)
    lines += ["] }", "",
              f"// {total} test methods",
              "MainActor.assumeIsolated {",
              "    exit(runXCTestSuites(xctestSuiteEntries()))",
              "}"]
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {total} test entries to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
